import test from 'node:test'
import assert from 'node:assert/strict'
import { readFile } from 'node:fs/promises'
import { resolve } from 'node:path'

const skillPath = resolve(import.meta.dirname, '../skills/pmd-prd/SKILL.md')
const capabilityMatrixPath = resolve(import.meta.dirname, '../skills/pmd-prd/references/capability-matrix.md')
const processStatePath = resolve(import.meta.dirname, '../skills/pmd-prd/references/process-state.md')

test('pmd-prd审查需求是否混装，并在资料选择前要求拆分决策', async () => {
  const skill = await readFile(skillPath, 'utf8')
  const capabilityMatrix = await readFile(capabilityMatrixPath, 'utf8')
  const processState = await readFile(processStatePath, 'utf8')
  const gate = skill.indexOf('### 阶段 1：输入需求')
  const references = skill.indexOf('### 阶段 2：选择参考资料')
  const gateText = skill.slice(gate, references)
  const preflight = gateText.indexOf('需求聚合预检是收到新业务需求后的第一判断')
  const preflightSettled = gateText.indexOf('完成条件：无混装')
  const runInitialization = gateText.indexOf('此时 Harness 才自动生成内部 `requirementId`')
  const quantification = gateText.indexOf('才建立“问题基线/规模')

  assert.ok(gate >= 0 && references > gate, '阶段1必须位于阶段2之前')
  assert.ok(preflight >= 0, '阶段1必须先声明无状态聚合预检')
  assert.ok(preflightSettled > preflight, '聚合预检必须有明确结算条件')
  assert.ok(runInitialization > preflightSettled, 'Run初始化必须晚于聚合预检结算')
  assert.ok(quantification > preflightSettled, '价值量化必须晚于聚合预检结算')
  assert.match(gateText, /只有一个功能点时直接通过；至少两个功能点时/)
  assert.match(gateText, /同一用户旅程/)
  assert.match(gateText, /优先级或发布单元/)
  assert.match(gateText, /多个功能点不自动等于多个需求/)
  assert.match(gateText, /独立上线、独立排期或独立验收/)
  assert.match(gateText, /“优化需求”“本次迭代”“一起做”“放在同一份 PRD”等说法只代表打包偏好/)
  assert.match(gateText, /即使用户已说“都放进本次优化需求”/)
  assert.match(gateText, /拆成独立 PRD（推荐）.*共同且不可拆的业务目标/)
  assert.match(gateText, /不进行价值量化、资料选择、研究或后续阶段规划/)
  assert.match(gateText, /不读取 `process-state\.md`、模板或其他文件/)
  assert.match(gateText, /不生成 `requirementId`/)
  assert.match(gateText, /不创建工作区或写过程文件/)
  assert.match(gateText, /pmd_prd_requirement_aggregation/)
  assert.match(gateText, /不得先输出解释或调用其他工具/)
  assert.match(gateText, /当前 Run 仍只产一份 PRD/)
  assert.match(gateText, /本轮主需求/)
  assert.match(gateText, /后续独立 Run 候选/)
  assert.match(gateText, /首次状态初始化中把这些候选的简短摘要批量记入 `process\.md`/)
  assert.match(gateText, /候选不属于当前 PRD 范围/)
  assert.match(gateText, /共同目标、范围边界和各子项独立验收/)
  assert.match(skill, /`aggregation_preflight → input → reference_selection/)
  assert.match(skill, /聚合预检等待拆分\/保留决定时不读取该文件/)
  assert.doesNotMatch(skill, /本条消息包含普通新需求时，直接生成本 Run 的新内部标识并创建对应目录/)
  assert.match(processState, /聚合预检未结算时尚未启动 Run，不读取本文件，也不创建或更新任何过程状态/)
  assert.match(processState, /聚合预检及其拆分\/保留问答发生在 Run 之前，不属于状态转换，不写过程文件/)
  assert.match(processState, /其余功能点的简短摘要批量写入 `process\.md` 的“后续独立需求候选”/)
  assert.match(processState, /不创建额外文档/)
  assert.match(capabilityMatrix, /1 输入需求 \| `aggregation_preflight → input`/)
  assert.match(capabilityMatrix, /混装未决时未启动 Run、未读取状态合同、未持久化或研究/)
  assert.match(capabilityMatrix, /其余候选在 Run 初始化后写入 `process\.md`/)
  assert.match(capabilityMatrix, /只算打包偏好，不能替代共同业务目标/)
  assert.match(capabilityMatrix, /拆分时已选定本轮主需求/)
})
