import assert from 'node:assert/strict'
import { access, readFile } from 'node:fs/promises'
import { dirname, resolve } from 'node:path'
import test from 'node:test'
import { fileURLToPath } from 'node:url'

const projectRoot = resolve(dirname(fileURLToPath(import.meta.url)), '..')
const workflowPath = resolve(projectRoot, '.github/workflows/build-windows-lite.yml')
test('Windows CI builds from the recursive upstream submodule and materialized product tree', async () => {
  const workflow = (await readFile(workflowPath, 'utf8')).replaceAll('\r\n', '\n')

  assert.match(workflow, /uses:\s*actions\/checkout@v4[\s\S]*?submodules:\s*recursive/)
  assert.equal(workflow.match(/uses:\s*actions\/checkout@v4/g)?.length, 1)
  assert.doesNotMatch(workflow, /repository:\s*deepseek-ai\/deepseek-harness/)
  assert.doesNotMatch(workflow, /harness-ui\.patch/)
  assert.doesNotMatch(workflow, /git\s+-C\s+deepseek-harness\s+apply/)

  assert.match(workflow, /working-directory:\s*deepseek_harness_chrome[\s\S]*?run:\s*pnpm install --frozen-lockfile/)
  assert.match(workflow, /run:\s*pnpm verify:upstream/)
  assert.match(workflow, /run:\s*pnpm build:harness-product/)
  assert.match(workflow, /--source \.generated\/harness-product/)
  assert.match(workflow, /--revision \$\{\{ steps\.upstream-hash\.outputs\.sha \}\}/)
  assert.match(workflow, /pnpm materialize:windows-harness-static-runtime --/)
  assert.doesNotMatch(workflow, /pnpm materialize:windows-harness-runtime --/)
  assert.doesNotMatch(workflow, /harness-runtime-win32-x64/)
  assert.match(workflow, /harness-static-win32-x64/)
  assert.doesNotMatch(workflow, /Cache harness product/)
  assert.doesNotMatch(workflow, /cache-harness-product/)
  assert.match(workflow, /Build materialized Harness product[\s\S]*?if: steps\.cache-harness-static-runtime\.outputs\.cache-hit != 'true'/)
  assert.match(workflow, /actions\/cache\/restore@v4/)
  assert.match(workflow, /actions\/cache\/save@v4/)
  assert.match(workflow, /cache-primary-key/)
  assert.match(workflow, /windows-lite-ready-v2-/)
  assert.match(workflow, /release\/windows-lite\/build-static-harness-runtime\.mjs/)
  assert.doesNotMatch(workflow, /release\/windows-lite\/\*\*/)
  assert.match(workflow, /Build release-ready extension[\s\S]*?run: pnpm build/)
  assert.match(workflow, /apps\/chrome-extension\/\.output\/chrome-mv3/)
  assert.match(workflow, /packages\/\*\/lib/)
  assert.doesNotMatch(workflow, /actions\/upload-artifact/)
  assert.match(workflow, /publish_public:\n\s+description: Publish the public update only after real Windows Chrome\/Edge UAT passes\n\s+required: false\n\s+type: boolean\n\s+default: false/)
  assert.match(workflow, /uat_candidate_commit:\n\s+description: Exact draft candidate commit approved by Windows Chrome\/Edge UAT/)
  assert.match(workflow, /uat_candidate_sha256:\n\s+description: Exact candidate ZIP SHA256 approved by Windows Chrome\/Edge UAT/)
  assert.match(workflow, /concurrency:\n\s+group: windows-lite-stable-publication\n\s+cancel-in-progress: false/)
  assert.match(workflow, /Upload Windows package to draft candidate/)
  assert.match(workflow, /- name: Accept locally built Windows candidate\n[\s\S]*?if: \$\{\{ inputs\.full_validation == true && inputs\.publish_public != true \}\}/)
  assert.match(workflow, /Validate public promotion and download exact UAT candidate/)
  assert.match(workflow, /Accept exact downloaded UAT candidate/)
  assert.match(workflow, /Promote exact UAT candidate to published release/)
  assert.match(workflow, /Write update manifest from exact UAT candidate/)
  assert.match(workflow, /Publish strictly newer stable update manifest/)
  assert.match(workflow, /accr-ui-windows-lite-update\.json/)
  assert.match(workflow, /must be greater than highest published Windows Lite version/)
  assert.match(workflow, /windows-lite-current/)
  assert.match(workflow, /attempt -le 4/)
  assert.match(workflow, /function Assert-DraftCandidate/)
  assert.match(workflow, /must remain a draft; published or prerelease candidates cannot be changed/)
  assert.match(workflow, /UAT candidate .* must still be a draft; published or prerelease candidates are rejected/)
  assert.match(workflow, /UAT approval is bound to \$env:UAT_CANDIDATE_COMMIT, not this workflow commit \$env:RELEASE_SHA/)
  assert.match(workflow, /gh release download \$env:CANDIDATE_TAG --repo \$repo --pattern \$requiredAsset --dir \$promotionRoot/)
  assert.match(workflow, /Downloaded UAT candidate ZIP SHA256 \$candidateSha256 does not match approved SHA256/)
  assert.match(workflow, /release\/promotion-candidate\/accr-ui-windows-lite-x64\.zip/)
  assert.match(workflow, /Expand-Archive -LiteralPath \$candidateZip -DestinationPath \$candidatePackageRoot -Force/)
  assert.match(workflow, /-PackageDir \$candidatePackageDir/)
  assert.match(workflow, /function Upload-IfMissing\(\[string\]\$Asset, \[string\]\$Label\)/)
  assert.match(workflow, /Upload-IfMissing \$zip 'Published release ZIP upload'/)
  assert.match(workflow, /Upload-IfMissing \$checksum 'Published release checksum upload'/)
  assert.match(workflow, /gh release download \$env:RELEASE_TAG --repo \$repo --pattern \$assetName --dir \$recoveryRoot/)
  assert.match(workflow, /Existing immutable ZIP SHA256 differs from the UAT candidate/)
  assert.match(workflow, /Existing immutable checksum differs from the UAT candidate/)
  assert.match(workflow, /finally \{\s*Remove-Item -LiteralPath \$recoveryRoot/)
  assert.match(workflow, /Draft candidate creation[\s\S]*?gh release create \$env:RELEASE_TAG[\s\S]*?--draft/)
  assert.match(workflow, /- name: Reject public publication without full validation\n\s+if: \$\{\{ inputs\.publish_public == true \}\}/)
  assert.match(workflow, /publish_public=true requires full_validation=true/)
  assert.match(workflow, /- name: Upload Windows package to draft candidate\n\s+if: \$\{\{ inputs\.publish_public != true \}\}/)
  for (const step of ['Validate public promotion and download exact UAT candidate', 'Accept exact downloaded UAT candidate', 'Promote exact UAT candidate to published release', 'Write update manifest from exact UAT candidate', 'Publish strictly newer stable update manifest']) {
    assert.match(workflow, new RegExp(`- name: ${step}\\n\\s+if: \\$\\{\\{ inputs\\.full_validation == true && inputs\\.publish_public == true \\}\\}`))
  }
  assert.match(workflow, /targetCommitish/)
  assert.match(workflow, /Upload-IfMissing/)
  const install = workflow.indexOf('run: pnpm install --frozen-lockfile')
  const buildProduct = workflow.indexOf('run: pnpm build:harness-product')
  const buildExtension = workflow.indexOf('- name: Build release-ready extension')
  const materializeRuntime = workflow.indexOf('pnpm materialize:windows-harness-static-runtime --')
  const buildRelease = workflow.indexOf('node release/windows-lite/windows-release.mjs')
  const acceptRelease = workflow.indexOf('./release/windows-lite/acceptance-windows.ps1')
  const checksum = workflow.indexOf("$zip = 'release/accr-ui-windows-lite-x64.zip'")
  assert.ok(install < buildProduct && buildProduct < buildExtension && buildExtension < materializeRuntime && materializeRuntime < buildRelease)
  assert.ok(buildRelease < acceptRelease && acceptRelease < checksum)
  assert.match(workflow, /-ExpectedVersion "\$\{\{ inputs\.version \|\| '1\.1\.88' \}\}"/)
  const promotion = workflow.indexOf('- name: Promote exact UAT candidate to published release')
  const candidateUpload = workflow.indexOf('- name: Upload Windows package to draft candidate')
  const publicValidation = workflow.indexOf('- name: Validate public promotion and download exact UAT candidate')
  const exactCandidateAcceptance = workflow.indexOf('- name: Accept exact downloaded UAT candidate')
  const releaseTarget = workflow.indexOf('--target $env:UAT_CANDIDATE_COMMIT', promotion)
  const uploadRelease = workflow.indexOf('Upload-IfMissing $zip', promotion)
  const rereadStable = workflow.indexOf('Unable to re-read the current stable update manifest.')
  const uploadManifest = workflow.indexOf('gh release upload $env:CHANNEL_TAG $manifest --repo $repo --clobber')
  const candidateStep = workflow.slice(candidateUpload, publicValidation)
  const stableManifestStep = workflow.slice(workflow.indexOf('- name: Publish strictly newer stable update manifest'))
  assert.doesNotMatch(candidateStep, /--clobber/)
  assert.match(candidateStep, /release\/candidate-canonical/)
  assert.match(candidateStep, /Existing draft candidate ZIP and checksum disagree; refusing to clobber either asset/)
  assert.doesNotMatch(stableManifestStep, /gh release edit/)
  assert.ok(publicValidation < exactCandidateAcceptance && exactCandidateAcceptance < promotion)
  assert.ok(promotion >= 0 && promotion < releaseTarget && releaseTarget < uploadRelease)
  assert.ok(rereadStable >= 0 && rereadStable < uploadManifest)
  assert.match(workflow, /\[version\]\$env:RELEASE_VERSION -le \[version\]\$currentManifest\.version/)
  assert.match(workflow, /Windows runner verified install, Chrome\/Edge Native Messaging registration, ping\/pong, upgrade, rollback, and user-data retention/)
  assert.match(workflow, /Visual Chrome\/Edge sidepanel UAT on a target Windows machine remains required/)
  assert.doesNotMatch(workflow, /Real Windows installation, Native Messaging, upgrade, and rollback acceptance are still required/)
  await assert.rejects(access(resolve(projectRoot, 'release/windows-lite/harness-ui.patch')))
})
