import assert from 'node:assert/strict'
import { readFile } from 'node:fs/promises'
import test from 'node:test'

const root = new URL('.', import.meta.url)
const main = await readFile(new URL('./main.tsx', root), 'utf8')
const background = await readFile(new URL('../background.ts', root), 'utf8')
const editor = await readFile(new URL('./visual-markdown-editor.tsx', root), 'utf8')
const mermaidView = await readFile(new URL('./mermaid-view.mjs', root), 'utf8')
const style = await readFile(new URL('./style.css', root), 'utf8')
const wxtConfig = await readFile(new URL('../../wxt.config.ts', root), 'utf8')
const packageJson = JSON.parse(await readFile(new URL('../../package.json', root), 'utf8'))

test('development prebundles the CommonJS debug dependency used by micromark', () => {
  assert.match(wxtConfig, /include:\s*\[[\s\S]*['"]@milkdown\/crepe['"][\s\S]*['"]@milkdown\/kit['"]/)
  assert.match(wxtConfig, /['"]@milkdown\/kit\/core['"][\s\S]*['"]@milkdown\/kit\/plugin\/diff['"][\s\S]*['"]@milkdown\/kit\/plugin\/history['"][\s\S]*['"]@milkdown\/kit\/plugin\/streaming['"][\s\S]*['"]@milkdown\/kit\/prose\/state['"][\s\S]*['"]@milkdown\/kit\/prose\/view['"][\s\S]*['"]@milkdown\/kit\/utils['"]/)
  assert.match(wxtConfig, /include:\s*\[[\s\S]*['"]debug['"]/)
  assert.equal(packageJson.dependencies.debug, '4.4.3')
})

test('review workspace uses one visual Milkdown canvas rather than source and preview panes', () => {
  assert.match(main, /<VisualMarkdownEditor/)
  assert.match(main, /在排版后的正文中直接编辑/)
  assert.doesNotMatch(main, /SourceEditor|SafeMarkdownPreview|ReactMarkdown/)
  assert.match(style, /\.visual-markdown-editor/)
})

test('review chrome stays compact and replaces empty error canvases with recovery state', () => {
  assert.match(main, /showRecoveryState/)
  assert.match(main, /const activityNotice =/)
  assert.match(main, /activityNotice !== undefined/)
  assert.match(main, /setAiTarget\(undefined\)/)
  assert.match(main, /setSidePanelRecoveryAnnotation\(undefined\)/)
  assert.match(main, /review-recovery/)
  assert.doesNotMatch(main, /className="workspace-toolbar"/)
  assert.match(style, /\.review-header\s*\{[\s\S]*height: 44px;/)
  assert.match(style, /\.review-main\s*\{[\s\S]*padding: 0;/)
  assert.match(style, /\.review-recovery\s*\{/)
  assert.match(main, /title="在排版后的正文中直接编辑；标题、段落、列表、表格、代码块和跨块选区都可作为 AI 上下文。HTML 保留为安全文本；Mermaid 仅在本地安全渲染。"/)
})

test('review actions use icon history controls and route rewrite or accept through the bound session', () => {
  assert.match(main, /aria-label="撤销（Ctrl\+Z）"/)
  assert.match(main, /aria-label="重做（Ctrl\+Y）"/)
  assert.match(main, /aria-label="重新读取"/)
  assert.match(main, />↶<\/button>/)
  assert.match(main, />↷<\/button>/)
  assert.match(main, />↻<\/button>/)
  assert.match(main, /↺ 重写/)
  assert.match(main, /✓ 采纳/)
  assert.match(main, /className="review-session-action is-rewrite"/)
  assert.match(main, /className="review-session-action is-accept"/)
  assert.match(main, /markdown-review-session-action-request/)
  assert.match(main, /harnessSessionId: activeSnapshot\.harnessSessionId/)
  assert.match(main, /expected\?\.kind !== 'session-action'/)
  assert.match(main, /MARKDOWN_REVIEW_DELIVERY_TIMEOUT_MS/)
  assert.match(background, /reportPrdReviewAction\(record, message\.requestId, message\.action, 'succeeded', action\.status\)/)
  assert.match(background, /未在\.\{0,20\}秒[\s\S]*'timeout' : 'failed'/)
  assert.match(style, /\.review-header-actions \.icon-button/)
  assert.match(style, /\.review-session-action\.is-rewrite\s*\{\s*background: var\(--review-danger-action\)/)
  assert.match(style, /\.review-session-action\.is-accept\s*\{\s*background: var\(--review-success-action\)/)
  assert.match(style, /\.review-session-action\.is-rewrite:hover:not\(:disabled\)/)
  assert.match(style, /\.review-session-action\.is-accept:hover:not\(:disabled\)/)
  assert.match(style, /\.review-session-action\.is-rewrite:focus-visible/)
  assert.match(style, /\.review-session-action\.is-accept:focus-visible/)
})

test('visual surface states the safe HTML downgrade and local Mermaid preview', () => {
  assert.match(main, /HTML 保留为安全文本；Mermaid 仅在本地安全渲染。/)
  assert.doesNotMatch(main, /data-source-start|data-source-end/)
})

test('each Mermaid block defaults to a visual view and can independently reveal its unchanged source', () => {
  assert.match(editor, /mermaid-view-toggle/)
  assert.match(editor, /可视化/)
  assert.match(editor, /源码/)
  assert.match(editor, /data-mermaid-source/)
  assert.match(editor, /wireMermaidViewToggle/)
  assert.match(editor, /Decoration\.node/)
  assert.match(mermaidView, /classList\.toggle\('mermaid-source-hidden'/)
  assert.match(mermaidView, /aria-pressed/)
  assert.doesNotMatch(editor, /onMarkdownChangeRef\.current\(source\)/)
  assert.match(editor, /key: `mermaid:\$\{position\}:\$\{node\.textContent\}`/)
  assert.match(editor, /Decoration\.widget\(position, /)
  assert.match(editor, /mermaid-viewer-controls/)
  assert.match(editor, /wireMermaidViewer/)
  assert.match(editor, /全屏/)
  assert.match(editor, /退出全屏/)
  assert.match(editor, /wireMermaidFullscreen/)
  assert.doesNotMatch(mermaidView, /requestFullscreen/)
  assert.match(mermaidView, /is-fullscreen-fallback/)
  assert.match(mermaidView, /event\.key !== 'Escape'/)
  assert.match(style, /\.mermaid-toolbar\s*\{[\s\S]*justify-content: space-between/)
  assert.match(style, /\.mermaid-canvas\s*\{[\s\S]*transform-origin: center/)
  assert.match(style, /\.mermaid-block\.is-fullscreen-fallback/)
  assert.match(style, /\.mermaid-viewer-controls button\[hidden\]\s*\{\s*display: none !important/)
})

test('official Crepe code and image blocks retain their component layout instead of falling back to raw pre and img styling', () => {
  assert.match(style, /\.milkdown-code-block\s*\{[\s\S]*border: 1px solid var\(--review-border\)/)
  assert.match(style, /\.milkdown-code-block \.tools\s*\{[\s\S]*border-bottom: 1px solid var\(--review-border-subtle\)/)
  assert.match(style, /\.milkdown-image-block\s*\{[\s\S]*max-inline-size: min\(100%, 960px\)/)
  assert.match(style, /\.milkdown-image-block .*img\s*\{[\s\S]*max-block-size: 640px/)
  assert.match(style, /\.mermaid-block\s*\{[\s\S]*width: 100%/)
  assert.match(style, /\.mermaid-preview\s*\{[\s\S]*width: 100%(?![\s\S]*max-width: 960px)/)
})

test('table cell text does not inherit a rounded editor box from generic node selection styling', () => {
  assert.match(style, /\.visual-markdown-editor \.milkdown \.ProseMirror table\s*\{[\s\S]*border-collapse:\s*collapse/)
  assert.match(style, /\.visual-markdown-editor \.milkdown \.ProseMirror th,\s*\.visual-markdown-editor \.milkdown \.ProseMirror td\s*\{[\s\S]*border:\s*1px solid/)
  assert.match(style, /\.visual-markdown-editor \.milkdown \.ProseMirror table (?:th|td)\s*>\s*\.ProseMirror-selectednode\s*\{[\s\S]*outline:\s*none !important;[\s\S]*box-shadow:\s*none !important;[\s\S]*border-radius:\s*0 !important/)
  assert.match(style, /\.visual-markdown-editor \.milkdown \.ProseMirror table (?:th|td):has\(> \.ProseMirror-selectednode\)\s*\{[\s\S]*outline:\s*1px solid/)
})

test('active AI diffs show before and after with visible accept and reject controls', () => {
  assert.match(main, /candidateReviewActive/)
  assert.match(main, /修改前/)
  assert.match(main, /修改后/)
  assert.match(main, /拒绝修改/)
  assert.match(main, /接受修改/)
  assert.match(main, /acceptCandidate/)
  assert.match(main, /rejectCandidate/)
  assert.match(style, /\.diff-review-dock/)
  assert.match(style, /\.milkdown-diff-controls/)
  assert.match(style, /display: none !important/)
})

test('dirty visual drafts use a captured selection and explicit verified-write confirmation', () => {
  assert.match(main, /annotationSelectionsRef/)
  assert.match(main, /reviewSelectionReplacement\(saved, proposal\.replacementMarkdown\)/)
  assert.match(main, /编辑版本、范围或选中文本已变化/)
  assert.match(main, /markdown-review-prepare-write-request/)
  assert.match(main, /确认写入/)
  assert.match(main, /markdown-review-commit-write-request/)
  assert.match(main, /同一资源回读验证/)
  assert.match(main, /不会自动重试/)
})

test('external updates preserve local review work and a write confirmation cannot double-commit', () => {
  assert.match(main, /hasLocalReviewWork\(\)/)
  assert.match(main, /外部文件已更新/)
  assert.match(main, /放弃本地更改并重新读取/)
  assert.match(main, /syncEditorMarkdown\(\)/)
  assert.match(main, /idempotencyKey: requestId\(\)/)
  assert.match(main, /beginCommit\(commitRef\.current/)
  assert.match(main, /isCurrentCommit\(commitRef\.current, expected\.token\)/)
  assert.match(main, /正在确认写入/)
})

test('write and external-update confirmations use accessible dialogs instead of top notices', () => {
  assert.match(main, /const activityNotice = preparedWrite === undefined && !externalUpdatePending \? saveNotice \?\? proposalNotice : proposalNotice/)
  assert.match(main, /preparedWrite !== undefined && <div className="confirmation-dialog-backdrop">/)
  assert.match(main, /role="dialog" aria-modal="true" aria-labelledby="write-confirmation-title"/)
  assert.match(main, /id="write-confirmation-title">确认写入草稿/)
  assert.match(main, /将把当前草稿写入已核对的文件版本。/)
  assert.match(main, /const showExternalUpdateConfirmation = externalUpdatePending && preparedWrite === undefined/)
  assert.match(main, /showExternalUpdateConfirmation && <div className="confirmation-dialog-backdrop">/)
  assert.match(main, /role="dialog" aria-modal="true" aria-labelledby="external-update-confirmation-title"/)
  assert.match(main, /保留本地内容/)
  assert.match(main, /放弃本地更改并重新读取/)
  assert.doesNotMatch(main, /preparedWrite !== undefined && <section className="save-confirm"/)
  assert.doesNotMatch(main, /externalUpdatePending && <section className="save-confirm"/)
  assert.match(style, /\.confirmation-dialog-backdrop\s*\{[\s\S]*position: fixed;/)
  assert.match(style, /\.confirmation-dialog\s*\{[\s\S]*max-width: min\(420px, calc\(100vw - 32px\)\)/)
})

test('verified-save notices dismiss after five seconds, while all activity notices can be closed manually', () => {
  assert.match(main, /const VERIFIED_SAVE_NOTICE = '已保存，并已按同一资源回读验证。'/)
  assert.match(main, /const VERIFIED_SAVE_NOTICE_DISMISS_MS = 5_000/)
  assert.match(main, /setVerifiedSaveNoticeToken\(verifiedNoticeToken\); showSaveNotice\(VERIFIED_SAVE_NOTICE\)/)
  assert.match(main, /window\.setTimeout\(\(\) => \{[\s\S]*verifiedSaveNoticeTokenRef\.current !== token[\s\S]*setSaveNotice\(undefined\)[\s\S]*\}, VERIFIED_SAVE_NOTICE_DISMISS_MS\)/)
  assert.match(main, /activityNotice !== undefined && <section className="proposal-notice" role="status">[\s\S]*aria-label="关闭提示"/)
  assert.match(main, /const dismissActivityNotice = \(\) => \{[\s\S]*preparedWrite === undefined && !externalUpdatePending && saveNotice !== undefined[\s\S]*showSaveNotice\(undefined\)[\s\S]*return[\s\S]*setProposalNotice\(undefined\)/)
  assert.match(main, /sidePanelRecoveryAnnotation !== undefined && <button[\s\S]*打开侧边栏并重试/)
  assert.match(style, /\.proposal-notice-message\s*\{[\s\S]*flex: 1/)
  assert.match(style, /\.proposal-notice-close\s*\{[\s\S]*width: 28px/)
})

test('selection review is contextual inside the document instead of a fixed right panel', () => {
  assert.doesNotMatch(main, /annotation-panel|setReviewPanelOpen/)
  assert.doesNotMatch(style, /\.annotation-panel/)
  assert.match(editor, /pointerup/)
  assert.match(editor, /keyup/)
  assert.match(editor, /AI_SELECTION_QUICK_ACTIONS/)
  assert.match(editor, /润色/)
  assert.match(editor, /精简/)
  assert.match(editor, /扩写/)
  assert.match(editor, /转验收标准/)
  assert.match(editor, /submitQuickAction[\s\S]*onSubmitAnnotation\(floatingSelection, instruction\)/)
  assert.match(editor, /添加自定义批注/)
  assert.match(editor, /提交给 AI/)
  assert.match(style, /\.selection-action-menu/)
  assert.match(style, /\.selection-action/)
  assert.match(style, /\.annotation-composer/)
})

test('selection actions stay inside the review shell near its right edge', () => {
  assert.match(editor, /const shellBounds = shell\?\.getBoundingClientRect\(\)/)
  assert.match(editor, /const menuMaxWidth = Math\.min\(520, Math\.max\(0, shellBounds\.width - 16\)\)/)
  assert.match(editor, /left: Math\.max\(shellBounds\.left \+ 8, Math\.min\(anchor\.left, shellBounds\.right - menuMaxWidth - 8\)\)/)
  assert.match(editor, /style=\{\{ top: floatingSelection\.top, left: floatingSelection\.left, maxWidth: floatingSelection\.menuMaxWidth \}\}/)
  assert.match(style, /\.selection-action-menu\s*\{[\s\S]*flex-wrap: wrap;/)
  assert.doesNotMatch(style, /\.selection-action-menu\s*\{[\s\S]*overflow-x: auto;/)
  assert.match(editor, /aria-label="添加自定义批注"/)
})

test('saved annotations stay highlighted in the document and expose their delivery state', () => {
  assert.match(editor, /Decoration\.inline/)
  assert.match(editor, /data-review-annotation-id/)
  assert.match(style, /\.review-annotation-highlight/)
  assert.match(editor, /批注详情/)
  assert.match(editor, /statusAnnotation\.comment/)
  assert.match(editor, /重新发送/)
  assert.match(style, /\.annotation-status-popover p/)
  assert.match(editor, /已提交给 AI|正在提交给 AI|提交给 AI 失败/)
})

test('annotation delivery survives editor startup and reports a disconnected send', () => {
  assert.match(editor, /isReady:/)
  assert.match(editor, /onReady/)
  assert.match(main, /!editor\.isReady\(\)/)
  assert.match(main, /onReady=\{applyQueuedProposal\}/)
  assert.doesNotMatch(main, /onReady=\{[^}]*syncEditorMarkdown/)
  assert.match(main, /getMarkdown\(\)/)
  assert.match(main, /const failSendingAnnotations[\s\S]*deliveryStatus === 'sending'[\s\S]*deliveryStatus: 'failed'/)
  assert.match(main, /const disconnected = \(\) => \{[\s\S]*failSendingAnnotations/)
  assert.match(main, /deliveryTimeoutsRef/)
  assert.match(main, /window\.setTimeout\([\s\S]*deliveryStatus: 'failed'/)
  assert.match(main, /const submitAnnotation[\s\S]*deliverAnnotation\(annotation\)/)
  assert.doesNotMatch(main, /const addAnnotation/)
})

test('opening the Side Panel preserves the click gesture and waits for a cold start', () => {
  assert.match(main, /const sidePanelWindowIdRef = useRef<number \| undefined>\(undefined\)/)
  assert.match(main, /void chrome\.windows\.getCurrent\(\)\.then/)
  const retryHandler = main.match(/const openSidePanelAndRetry = useCallback\(async \(\) => \{([\s\S]*?)\n  \}, \[deliverAnnotation, loadSnapshot, sidePanelRecoveryAnnotation, snapshot\]\)/)?.[1]
  assert.notEqual(retryHandler, undefined)
  assert.match(retryHandler, /snapshot\?\.sidePanelTabId === undefined[\s\S]*chrome\.sidePanel\.open\(\{ tabId: snapshot\.sidePanelTabId \}\)/)
  assert.match(retryHandler, /await opened/)
  assert.doesNotMatch(retryHandler, /await chrome\.windows\.getCurrent/)
  assert.match(main, /SIDE_PANEL_STARTUP_RETRY_DELAYS_MS = \[500, 1_000, 2_000, 3_000\]/)
  assert.match(main, /error\.code === 'sidepanel_unavailable'[\s\S]*SIDE_PANEL_STARTUP_RETRY_DELAYS_MS/)
})

test('oversized visual selections are explained and never delivered', () => {
  assert.match(main, /selection\.limitReason !== undefined/)
  assert.match(editor, /quote_too_long/)
  assert.match(editor, /too_many_blocks/)
  assert.match(editor, /8,000/)
  assert.match(editor, /24/)
  assert.match(style, /\.selection-limit-notice/)
})

test('visual editing exposes undo and redo while retaining the native shortcuts', () => {
  assert.match(editor, /undoCommand/)
  assert.match(editor, /redoCommand/)
  assert.match(main, /撤销/)
  assert.match(main, /重做/)
  assert.match(main, /Ctrl\+Z/)
  assert.match(main, /Ctrl\+Y/)
  assert.match(main, /文件已绑定工作区/)
  assert.match(main, /打开侧边栏并重试/)
  assert.match(main, /已发送到“\$\{message\.targetSessionTitle\}”/)
  assert.match(editor, /已排队，等待当前会话完成/)
  assert.match(editor, /AI 候选已返回，等待审阅/)
  assert.match(main, /key=\{editorEpoch\}/)
  assert.match(main, /setEditorEpoch\(\(epoch\) => epoch \+ 1\)/)
  assert.doesNotMatch(main, /key=\{`\$\{snapshot\.resource\.revision\}:\$\{snapshot\.resource\.fingerprint\}`\}/)
})
