import assert from 'node:assert/strict'
import { readFile } from 'node:fs/promises'
import test from 'node:test'
const source = path => readFile(new URL(path, import.meta.url), 'utf8')

test('renders through the picker child slot and desktop header action without a quick action', async () => {
  const [manifest, client, action, tree, bridge, host, filePath] = await Promise.all([
    source('../package.json'), source('../src/client/index.ts'), source('../src/client/WorkspaceReviewAction.tsx'), source('../src/client/WorkspaceReviewTree.tsx'), source('../src/client/bridge.ts'), source('../src/index.ts'), source('../src/client/workspace-file-path.mjs'),
  ])
  assert.match(manifest, /@accrui\/harness-ui-workspace-review/)
  assert.doesNotMatch(client, /settingsQuickActions|workspace-markdown-files|sidebar\.compact\.action/)
  assert.match(client, /accrui\.workspace-picker\.directory/)
  assert.match(client, /accrui\.workspace-picker\.directory\.actions/)
  assert.match(client, /sidebar\.workspaces\.header\.action/)
  assert.match(client, /useSessionForWorkspace/)
  assert.match(client, /useSyncExternalStore/)
  assert.match(client, /selectReadyWorkspaceDirectorySession/)
  assert.match(tree, /正在等待工作区目录就绪/)
  assert.match(client, /reviewFeedback/)
  assert.match(client, /boundWorkspaceReviewTarget/)
  assert.doesNotMatch(client, /sessions\.current/)
  assert.match(client, /ctx\.sessions\.open\(feedback\.harnessSessionId as SessionId\)/)
  assert.match(client, /submitWorkspaceMarkdown\(target\.targetSessionId, feedback\)/)
  assert.match(client, /status: target\.running \? 'queued' : 'processing'/)
  assert.match(client, /\.then\(\(\) => respondFeedback/)
  assert.match(client, /\.catch\(error => respondFeedback/)
  assert.match(action, /createWorkspaceReviewHeaderAction/)
  assert.doesNotMatch(action, /reportDirectoryDrawerState|workspace-review-directory-state\/v1/)
  assert.match(action, /setOpen\(true\)/)
  assert.match(action, /dshBrowserTargetSurface.*fullscreen-tab/)
  assert.match(action, /createPortal/)
  assert.match(action, /document\.body/, 'the fixed drawer must escape the header stacking context so the composer cannot cover it')
  assert.match(action, /<WorkspaceReviewTree/)
  assert.match(action, />目录</)
  assert.match(tree, /listWorkspaceMarkdown/)
  assert.match(tree, /openWorkspaceMarkdown/)
  assert.match(tree, /entry\.kind === 'markdown'/, 'only Markdown entries may open the review flow')
  assert.match(tree, /onOpenFile\(entry\.displayPath\)/, 'ordinary files must be system-openable from the directory')
  assert.match(client, /ctx\.workspaces\.openPath\(workspaceFilePath\(workspacePath, displayPath\)\)/)
  assert.match(filePath, /displayPath\.split\('\/'\)\.some\(part => part === '' \|\| part === '\.' \|\| part === '\.\.'\)/)
  assert.match(action, /在资源管理器中打开工作区/)
  assert.match(action, /刷新文件树/)
  assert.match(client, /WorkspaceReviewDirectoryActions/)
  assert.match(client, /chatFileMentions[\s\S]*register\(conversationMarkdown\)/)
  assert.match(client, /toolFileLinks[\s\S]*register\(toolMarkdown\)/)
  assert.match(client, /resolveWorkspaceMarkdown\(String\(owner\.sessionId\), owner\.cwd, value\)/)
  assert.match(client, /resolve:\s*resolveReview, resolveLink:\s*resolveReview/)
  assert.match(client, /openWorkspaceMarkdown\(sessionId, displayPath\)/)
  assert.match(client, /requestOpenReview\(window\.parent, bridge, review\)/)
  assert.doesNotMatch(tree, /treeToolbar|在资源管理器中打开工作区|刷新文件树/, 'the tree must not duplicate compact pane-header actions')
  assert.match(tree, /generation\.current\.isCurrent\(requestedGeneration\)/)
  assert.match(tree, /setTrees\(new Map\(\)\)/)
  assert.match(tree, /inFlight\.current\.has\(requestKey\)/)
  assert.match(tree, /inFlight\.current\.clear\(\)/)
  assert.match(tree, /finally \{[\s\S]*isCurrent\(requestedGeneration\)[\s\S]*delete\(requestKey\)/)
  assert.match(tree, /const requestedSession = sessionId[\s\S]*const requestedGeneration = generation\.current\.value[\s\S]*await openWorkspaceMarkdown\(requestedSession, path\)[\s\S]*isCurrent\(requestedGeneration\)[\s\S]*requestOpenReview/, 'an old Markdown-open result must not open or close the new workspace')
  assert.match(tree, /catch \(reason\) \{[\s\S]*isCurrent\(requestedGeneration\)[\s\S]*setError/, 'an old Markdown-open failure must not update the new workspace')
  assert.match(tree, /onClose\(\)/)
  assert.doesNotMatch(`${action}\n${tree}`, /🗂|📁|📝/)
  assert.match(bridge, /markdown-review-open\/v1/)
  assert.match(bridge, /dshWorkspaceReviewNonce/)
  assert.match(bridge, /markdown-review-feedback-accepted\/v1/)
  assert.match(bridge, /markdown-review-session-action\/v1/)
  assert.match(client, /input\.setDraft/)
  assert.match(client, /existing\.trim\(\) === '' \? addition : `\$\{existing\}/)
  assert.doesNotMatch(client, /input\.submit/)
  assert.match(client, /scopedConversation\.send\(acceptPrompt\(action\)\)/)
  assert.match(client, /return `\/pmd-prd 我已采纳当前审阅的 PRD/)
  assert.match(client, /请继续执行“同步到远程 doc 文档”步骤/)
  assert.doesNotMatch(client, /请按\/pmd-prd/)
  assert.doesNotMatch(client, new RegExp(['请按当前 Skill', '的下一步继续'].join(' ')))
  assert.match(host, /WORKSPACE_REVIEW_SNAPSHOT_PATH/)
  assert.match(host, /isTrustedSessionRequest/)
  assert.match(host, /bearer\(req\)/)
  assert.match(host, /name: 'propose_workspace_markdown_edit'/)
  assert.match(host, /WORKSPACE_REVIEW_SELECTION_PATH/)
  assert.match(host, /WORKSPACE_REVIEW_PROPOSALS_PATH/)
  assert.match(host, /WORKSPACE_REVIEW_PREPARE_WRITE_PATH/)
  assert.match(host, /WORKSPACE_REVIEW_COMMIT_WRITE_PATH/)
  assert.doesNotMatch(`${client}\n${action}\n${tree}\n${bridge}`, /viewer registry|composerSubmissionTransforms|WorkspaceReviewStore|deepseek-harness\/packages\/.*\/src/i)
})

test('does not maintain a second local feedback store or a composer transform', async () => {
  const files = await Promise.all([
    source('../src/client/index.ts'), source('../src/client/bridge.ts'),
  ])
  assert.doesNotMatch(files.join('\n'), /setItem|localStorage|sessionStorage|composerSubmissionTransforms|WorkspaceReviewStore/)
})
