/** The only model-to-preview contract: bounded data, never executable code. */
export const PROTOTYPE_DOCUMENT_VERSION = 1 as const
export const MAX_REFERENCE_EVIDENCE = 12
export const MAX_SCREENS = 12
export const MAX_NODES = 240
export const MAX_TEXT_LENGTH = 2_000
export const MAX_URL_LENGTH = 2_048
export const MAX_DOCUMENT_JSON_BYTES = 200_000
export const MAX_DOCUMENT_TEXT_BYTES = 24_000

export type PrototypeActionType = 'navigate' | 'open-modal' | 'close-modal' | 'set-value' | 'toggle' | 'set-tab' | 'submit-success'
export type PrototypeNodeType = 'text' | 'button' | 'input' | 'card' | 'tabs' | 'list' | 'modal'
export interface ReferenceEvidenceV1 { v: 1; id: string; source: { url: string; title: string; capturedAt: string }; viewport: { width: number; height: number; deviceScaleFactor: number }; observations: string[]; designTokens: { colors: string[]; fonts: string[]; radius: string[]; spacing: string[] }; fingerprint: string; screenshotFingerprint?: string; screenshotDataUrl?: string }
export interface DesignSpecV1 { v: 1; id: string; name: string; basedOnEvidenceIds: string[]; summary: string; colors: { name: string; value: string; usage: string }[]; typography: { fontFamily: string; headingWeight: number; bodySize: number }; spacing: { base: number; cardRadius: number }; principles: string[] }
export interface PrototypeActionV1 { type: PrototypeActionType; targetId?: string; targetScreenId?: string; value?: string }
interface PrototypeNodeBase { id: string; type: PrototypeNodeType; label?: string }
export interface PrototypeTextNodeV1 extends PrototypeNodeBase { type: 'text'; text: string; tone?: 'heading' | 'body' | 'caption' }
export interface PrototypeButtonNodeV1 extends PrototypeNodeBase { type: 'button'; label: string; variant?: 'primary' | 'secondary' | 'danger'; action?: PrototypeActionV1 }
export interface PrototypeInputNodeV1 extends PrototypeNodeBase { type: 'input'; label: string; placeholder?: string; value?: string; inputType?: 'text' | 'email' | 'password' | 'checkbox' }
export interface PrototypeCardNodeV1 extends PrototypeNodeBase { type: 'card'; children: PrototypeNodeV1[] }
export interface PrototypeListItemV1 { id: string; title: string; detail?: string; action?: PrototypeActionV1 }
export interface PrototypeListNodeV1 extends PrototypeNodeBase { type: 'list'; items: PrototypeListItemV1[] }
export interface PrototypeTabV1 { id: string; label: string; children: PrototypeNodeV1[]; action?: PrototypeActionV1 }
export interface PrototypeTabsNodeV1 extends PrototypeNodeBase { type: 'tabs'; tabs: PrototypeTabV1[] }
export interface PrototypeModalNodeV1 extends PrototypeNodeBase { type: 'modal'; title: string; children: PrototypeNodeV1[] }
export type PrototypeNodeV1 = PrototypeTextNodeV1 | PrototypeButtonNodeV1 | PrototypeInputNodeV1 | PrototypeCardNodeV1 | PrototypeListNodeV1 | PrototypeTabsNodeV1 | PrototypeModalNodeV1
export interface PrototypeScreenV1 { id: string; title: string; nodes: PrototypeNodeV1[] }
export interface PrototypeDocumentV1 { v: 1; id: string; title: string; designSpecId: string; initialScreenId: string; screens: PrototypeScreenV1[] }
export interface PrototypeBundleV1 { evidence: ReferenceEvidenceV1[]; designSpec: DesignSpecV1; document: PrototypeDocumentV1 }
export interface PrototypeRevisionV1 { v: 1; id: string; prototypeId: string; parentRevisionId?: string; createdAt: string; author: 'agent' | 'user'; document: PrototypeDocumentV1; documentFingerprint: string; referenceEvidenceFingerprints: string[]; designSpecFingerprint: string; changeSummary: string }
export interface ValidationSuccess<T> { ok: true; value: T }
export interface ValidationFailure { ok: false; errors: string[] }
export type ValidationResult<T> = ValidationSuccess<T> | ValidationFailure

const ids = /^[a-z][a-z0-9_-]{0,79}$/
const hash = /^[0-9a-f]{64}$/
const color = /^(#[0-9a-fA-F]{3,8}|rgba?\([^)]{1,50}\)|hsla?\([^)]{1,60}\))$/
const object = (value: unknown): value is Record<string, unknown> => typeof value === 'object' && value !== null && !Array.isArray(value)
const id = (value: unknown): value is string => typeof value === 'string' && ids.test(value)
const text = (value: unknown, max = MAX_TEXT_LENGTH): value is string => typeof value === 'string' && value.length <= max
const array = (value: unknown, max: number): value is unknown[] => Array.isArray(value) && value.length <= max
const keys = (value: Record<string, unknown>, allowed: readonly string[]): boolean => Object.keys(value).every(key => allowed.includes(key))
const strings = (value: unknown, max: number, each = MAX_TEXT_LENGTH): value is string[] => array(value, max) && value.every(item => text(item, each))
const numberIn = (value: unknown, min: number, max: number): value is number => typeof value === 'number' && Number.isFinite(value) && value >= min && value <= max
const fail = <T>(...errors: string[]): ValidationResult<T> => ({ ok: false, errors })

function byteLength(value: unknown): number { return new TextEncoder().encode(JSON.stringify(value) ?? '').byteLength }
function stringBytes(value: unknown): number { if (typeof value === 'string') return new TextEncoder().encode(value).byteLength; if (Array.isArray(value)) return value.reduce<number>((total, item) => total + stringBytes(item), 0); if (object(value)) return Object.values(value).reduce<number>((total, item) => total + stringBytes(item), 0); return 0 }
function withinDocumentBudget(value: unknown): boolean { return byteLength(value) <= MAX_DOCUMENT_JSON_BYTES && stringBytes(value) <= MAX_DOCUMENT_TEXT_BYTES }

type ActionOwner = { kind: 'button' | 'list-item' | 'tab'; id: string; tabParentId?: string }
interface Registry { ids: Set<string>; screens: Set<string>; inputs: Map<string, PrototypeInputNodeV1>; modals: Set<string>; tabs: Map<string, Set<string>>; actions: Array<{ action: PrototypeActionV1; owner: ActionOwner }>; count: number; errors: string[] }
function addId(registry: Registry, value: unknown, label: string): value is string { if (!id(value) || registry.ids.has(value)) { registry.errors.push(`${label} id 无效或重复。`); return false }; registry.ids.add(value); return true }
function parseAction(value: unknown, owner: ActionOwner, registry: Registry): value is PrototypeActionV1 {
  if (!object(value) || !text(value.type, 32) || !['navigate', 'open-modal', 'close-modal', 'set-value', 'toggle', 'set-tab', 'submit-success'].includes(value.type)) { registry.errors.push('动作必须是受支持的固定动作。'); return false }
  const allowed = value.type === 'navigate' || value.type === 'submit-success' ? ['type', 'targetScreenId'] : value.type === 'toggle' ? ['type', 'targetId'] : ['type', 'targetId', 'value']
  if (!keys(value, allowed) || (value.targetId !== undefined && !id(value.targetId)) || (value.targetScreenId !== undefined && !id(value.targetScreenId)) || (value.value !== undefined && !text(value.value, 500))) { registry.errors.push('动作字段或目标 id 无效。'); return false }
  if ((value.type === 'navigate' || value.type === 'submit-success') && !id(value.targetScreenId)) registry.errors.push('页面动作必须指向真实页面。')
  if (!['navigate', 'submit-success'].includes(value.type) && !id(value.targetId)) registry.errors.push('组件动作必须指向真实组件。')
  if (['set-value', 'set-tab'].includes(value.type) && typeof value.value !== 'string') registry.errors.push('设值动作必须提供字符串 value。')
  if (owner.kind === 'tab' ? value.type !== 'set-tab' : value.type === 'set-tab') registry.errors.push('动作只能由对应的可点击控件执行。')
  registry.actions.push({ action: value as unknown as PrototypeActionV1, owner }); return registry.errors.length === 0
}
function node(value: unknown, registry: Registry, depth: number): value is PrototypeNodeV1 {
  registry.count += 1
  if (depth > 4 || registry.count > MAX_NODES || !object(value) || !addId(registry, value.id, '组件') || !text(value.type, 24)) { registry.errors.push('组件层级或数量超出限制。'); return false }
  const type = value.type
  if (type === 'text') return keys(value, ['id', 'type', 'text', 'tone']) && text(value.text) && (value.tone === undefined || ['heading', 'body', 'caption'].includes(String(value.tone)))
  if (type === 'button') { const ok = keys(value, ['id', 'type', 'label', 'variant', 'action']) && text(value.label, 160) && (value.variant === undefined || ['primary', 'secondary', 'danger'].includes(String(value.variant))); if (value.action !== undefined) parseAction(value.action, { kind: 'button', id: value.id as string }, registry); return ok }
  if (type === 'input') { const ok = keys(value, ['id', 'type', 'label', 'placeholder', 'value', 'inputType']) && text(value.label, 160) && (value.placeholder === undefined || text(value.placeholder, 240)) && (value.value === undefined || text(value.value, 500)) && (value.inputType === undefined || ['text', 'email', 'password', 'checkbox'].includes(String(value.inputType))); if (ok) registry.inputs.set(value.id as string, value as unknown as PrototypeInputNodeV1); return ok }
  if (type === 'card' || type === 'modal') { const modal = type === 'modal'; const children = array(value.children, 40) ? value.children : undefined; const ok = keys(value, modal ? ['id', 'type', 'title', 'children'] : ['id', 'type', 'label', 'children']) && (modal ? text(value.title, 160) : value.label === undefined || text(value.label, 160)) && children !== undefined; if (modal) registry.modals.add(value.id as string); if (ok && children !== undefined) for (const child of children) node(child, registry, depth + 1); return ok }
  if (type === 'list') { if (!keys(value, ['id', 'type', 'label', 'items']) || (value.label !== undefined && !text(value.label, 160)) || !array(value.items, 40)) return false; for (const item of value.items) { if (!object(item) || !keys(item, ['id', 'title', 'detail', 'action']) || !addId(registry, item.id, '列表项') || !text(item.title, 200) || (item.detail !== undefined && !text(item.detail, 600))) { registry.errors.push('列表项无效。'); continue }; if (item.action !== undefined) parseAction(item.action, { kind: 'list-item', id: item.id as string }, registry) }; return true }
  if (type === 'tabs') { if (!keys(value, ['id', 'type', 'label', 'tabs']) || (value.label !== undefined && !text(value.label, 160)) || !array(value.tabs, 8) || value.tabs.length === 0) return false; const tabIds = new Set<string>(); registry.tabs.set(value.id as string, tabIds); for (const tab of value.tabs) { if (!object(tab) || !keys(tab, ['id', 'label', 'children', 'action']) || !addId(registry, tab.id, 'Tab') || !text(tab.label, 80) || !array(tab.children, 40)) { registry.errors.push('Tab 无效。'); continue }; tabIds.add(tab.id as string); if (tab.action !== undefined) parseAction(tab.action, { kind: 'tab', id: tab.id as string, tabParentId: value.id as string }, registry); for (const child of tab.children) node(child, registry, depth + 1) }; return true }
  registry.errors.push(`不支持的组件：${String(type)}`); return false
}
function validateReferences(registry: Registry): void { for (const { action, owner } of registry.actions) { if ((action.type === 'navigate' || action.type === 'submit-success') && !registry.screens.has(action.targetScreenId!)) registry.errors.push('动作引用了不存在的页面。'); if ((action.type === 'open-modal' || action.type === 'close-modal') && !registry.modals.has(action.targetId!)) registry.errors.push('弹窗动作必须引用 modal。'); if (action.type === 'set-value') { const target = registry.inputs.get(action.targetId!); if (target === undefined || target.inputType === 'checkbox') registry.errors.push('set-value 必须引用非 checkbox input。') }; if (action.type === 'toggle') { const target = registry.inputs.get(action.targetId!); if (target?.inputType !== 'checkbox') registry.errors.push('toggle 必须引用 checkbox input。') }; if (action.type === 'set-tab') { const targets = registry.tabs.get(action.targetId!); if (targets === undefined || !targets.has(action.value!) || owner.tabParentId !== action.targetId || owner.id !== action.value) registry.errors.push('set-tab 必须由目标 tabs 内的对应 tab 执行。') } } }

/** Parse untrusted agent output and resolve every reference only after discovery. */
export function validatePrototypeDocument(value: unknown): ValidationResult<PrototypeDocumentV1> {
  if (!withinDocumentBudget(value)) return fail('原型文档总大小或总文本超过限制。')
  if (!object(value) || !keys(value, ['v', 'id', 'title', 'designSpecId', 'initialScreenId', 'screens']) || value.v !== 1 || !id(value.id) || !text(value.title, 160) || !id(value.designSpecId) || !id(value.initialScreenId) || !array(value.screens, MAX_SCREENS) || value.screens.length === 0) return fail('原型文档不是受支持的 V1 格式。')
  const registry: Registry = { ids: new Set([value.id]), screens: new Set(), inputs: new Map(), modals: new Set(), tabs: new Map(), actions: [], count: 0, errors: [] }
  for (const screen of value.screens) { if (!object(screen) || !keys(screen, ['id', 'title', 'nodes']) || !addId(registry, screen.id, '页面') || !text(screen.title, 160) || !array(screen.nodes, 80)) { registry.errors.push('页面格式无效。'); continue }; registry.screens.add(screen.id as string); for (const item of screen.nodes) if (!node(item, registry, 0)) registry.errors.push('页面包含不受支持组件或字段。') }
  if (!registry.screens.has(value.initialScreenId)) registry.errors.push('初始页面不存在。'); validateReferences(registry)
  return registry.errors.length === 0 ? { ok: true, value: value as unknown as PrototypeDocumentV1 } : fail(...registry.errors)
}
export function isIsoDate(value: unknown): value is string { return typeof value === 'string' && /^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}\.\d{3}Z$/.test(value) && Number.isFinite(Date.parse(value)) && new Date(value).toISOString() === value }
export function validateReferenceEvidence(value: unknown): ValidationResult<ReferenceEvidenceV1> { if (!object(value) || !keys(value, ['v', 'id', 'source', 'viewport', 'observations', 'designTokens', 'fingerprint', 'screenshotFingerprint', 'screenshotDataUrl']) || value.v !== 1 || !id(value.id) || !object(value.source) || !keys(value.source, ['url', 'title', 'capturedAt']) || !text(value.source.url, MAX_URL_LENGTH) || !/^https?:\/\//.test(value.source.url) || !text(value.source.title, 240) || !isIsoDate(value.source.capturedAt) || !object(value.viewport) || !keys(value.viewport, ['width', 'height', 'deviceScaleFactor']) || !numberIn(value.viewport.width, 1, 20_000) || !numberIn(value.viewport.height, 1, 20_000) || !numberIn(value.viewport.deviceScaleFactor, .25, 8) || !strings(value.observations, 40, 600) || !object(value.designTokens) || !keys(value.designTokens, ['colors', 'fonts', 'radius', 'spacing']) || !strings(value.designTokens.colors, 24, 80) || !value.designTokens.colors.every(item => color.test(item)) || !strings(value.designTokens.fonts, 12, 120) || !strings(value.designTokens.radius, 12, 80) || !strings(value.designTokens.spacing, 12, 80) || !text(value.fingerprint, 64) || !hash.test(value.fingerprint) || (value.screenshotFingerprint !== undefined && (!text(value.screenshotFingerprint, 64) || !hash.test(value.screenshotFingerprint))) || (value.screenshotDataUrl !== undefined && (!text(value.screenshotDataUrl, 2_000_000) || !/^data:image\/(png|jpeg);base64,/.test(value.screenshotDataUrl)))) return fail('参考网页证据格式无效或超过大小限制。'); return { ok: true, value: value as unknown as ReferenceEvidenceV1 } }
export function validateDesignSpec(value: unknown, authorizedEvidenceIds: readonly string[]): ValidationResult<DesignSpecV1> { if (authorizedEvidenceIds.length === 0 || new Set(authorizedEvidenceIds).size !== authorizedEvidenceIds.length || !authorizedEvidenceIds.every(id)) return fail('设计规范必须有非空、去重的已授权参考证据。'); if (!object(value) || !keys(value, ['v', 'id', 'name', 'basedOnEvidenceIds', 'summary', 'colors', 'typography', 'spacing', 'principles']) || value.v !== 1 || !id(value.id) || !text(value.name, 120) || !strings(value.basedOnEvidenceIds, MAX_REFERENCE_EVIDENCE, 80) || value.basedOnEvidenceIds.length === 0 || new Set(value.basedOnEvidenceIds).size !== value.basedOnEvidenceIds.length || !value.basedOnEvidenceIds.every(item => id(item) && authorizedEvidenceIds.includes(item)) || !text(value.summary, 1_200) || !array(value.colors, 16) || value.colors.length === 0 || !value.colors.every(item => object(item) && keys(item, ['name', 'value', 'usage']) && text(item.name, 80) && text(item.value, 80) && color.test(item.value) && text(item.usage, 240)) || !object(value.typography) || !keys(value.typography, ['fontFamily', 'headingWeight', 'bodySize']) || !text(value.typography.fontFamily, 160) || !numberIn(value.typography.headingWeight, 100, 1_000) || !numberIn(value.typography.bodySize, 8, 96) || !object(value.spacing) || !keys(value.spacing, ['base', 'cardRadius']) || !numberIn(value.spacing.base, 0, 64) || !numberIn(value.spacing.cardRadius, 0, 80) || !strings(value.principles, 12, 240)) return fail('设计规范格式无效或未绑定已授权证据。'); return { ok: true, value: value as unknown as DesignSpecV1 } }
export function validatePrototypeBundle(value: unknown): ValidationResult<PrototypeBundleV1> { if (!object(value) || !keys(value, ['evidence', 'designSpec', 'document']) || !array(value.evidence, MAX_REFERENCE_EVIDENCE) || value.evidence.length === 0) return fail('原型必须带已授权参考证据和设计规范。'); const evidence: ReferenceEvidenceV1[] = []; for (const item of value.evidence) { const checked = validateReferenceEvidence(item); if (!checked.ok) return checked; evidence.push(checked.value) }; if (new Set(evidence.map(item => item.id)).size !== evidence.length) return fail('参考证据 id 重复。'); const designSpec = validateDesignSpec(value.designSpec, evidence.map(item => item.id)); if (!designSpec.ok) return designSpec; const document = validatePrototypeDocument(value.document); if (!document.ok) return document; if (document.value.designSpecId !== designSpec.value.id) return fail('原型 document.designSpecId 必须匹配当前设计规范。'); return { ok: true, value: { evidence, designSpec: designSpec.value, document: document.value } } }
export interface PrototypeDesignTokens { primary: string; surface: string; radius: string; font: string; bodySize: string; headingWeight: number }
export function prototypeDesignTokens(spec: DesignSpecV1): PrototypeDesignTokens { const allowedFonts = new Set(['system-ui', 'ui-sans-serif', 'sans-serif', 'Arial', 'Inter', 'PingFang SC']); return { primary: spec.colors[0]?.value ?? '#2563eb', surface: spec.colors[1]?.value ?? '#ffffff', radius: `${spec.spacing.cardRadius}px`, font: allowedFonts.has(spec.typography.fontFamily) ? spec.typography.fontFamily : 'system-ui', bodySize: `${spec.typography.bodySize}px`, headingWeight: spec.typography.headingWeight } }
export function collectPrototypeElementIds(document: PrototypeDocumentV1): Set<string> { const result = new Set<string>(); const visit = (node: PrototypeNodeV1) => { result.add(node.id); if (node.type === 'card' || node.type === 'modal') node.children.forEach(visit); if (node.type === 'list') node.items.forEach(item => result.add(item.id)); if (node.type === 'tabs') node.tabs.forEach(tab => { result.add(tab.id); tab.children.forEach(visit) }) }; document.screens.forEach(screen => screen.nodes.forEach(visit)); return result }
function canonical(value: unknown): unknown { if (Array.isArray(value)) return value.map(canonical); if (object(value)) return Object.fromEntries(Object.keys(value).sort().map(key => [key, canonical(value[key])])); return value }
export function canonicalJson(value: unknown): string { return JSON.stringify(canonical(value)) }
export async function sha256Fingerprint(value: unknown): Promise<string> { const digest = await crypto.subtle.digest('SHA-256', new TextEncoder().encode(canonicalJson(value))); return [...new Uint8Array(digest)].map(byte => byte.toString(16).padStart(2, '0')).join('') }
/** Mirrors the trusted capture projection; agents cannot substitute this calculation. */
export async function computeReferenceEvidenceFingerprint(evidence: ReferenceEvidenceV1): Promise<string> { const content = { v: 1, source: { url: evidence.source.url, title: evidence.source.title }, viewport: evidence.viewport, observations: evidence.observations, designTokens: evidence.designTokens, ...(evidence.screenshotFingerprint === undefined ? {} : { screenshotFingerprint: evidence.screenshotFingerprint }) }; const digest = await crypto.subtle.digest('SHA-256', new TextEncoder().encode(JSON.stringify(content))); return [...new Uint8Array(digest)].map(byte => byte.toString(16).padStart(2, '0')).join('') }
export async function verifyReferenceEvidenceFingerprint(evidence: ReferenceEvidenceV1): Promise<boolean> { return (await computeReferenceEvidenceFingerprint(evidence)) === evidence.fingerprint }
export interface CreateTrustedRevisionInput { id: string; parentRevisionId?: string; author: 'agent' | 'user'; document: unknown; designSpec: unknown; evidence: readonly unknown[]; changeSummary: string; createdAt?: string }
export async function createTrustedRevision(input: CreateTrustedRevisionInput): Promise<ValidationResult<PrototypeRevisionV1>> { const bundle = validatePrototypeBundle({ evidence: [...input.evidence], designSpec: input.designSpec, document: input.document }); if (!bundle.ok || !id(input.id) || (input.parentRevisionId !== undefined && !id(input.parentRevisionId)) || !['agent', 'user'].includes(input.author) || !text(input.changeSummary, 600)) return fail('无法创建可信原型版本。'); if (!(await Promise.all(bundle.value.evidence.map(verifyReferenceEvidenceFingerprint))).every(Boolean)) return fail('参考证据指纹未通过可信计算。'); const createdAt = input.createdAt ?? new Date().toISOString(); if (!isIsoDate(createdAt)) return fail('版本创建时间必须是 ISO UTC 时间。'); return { ok: true, value: { v: 1, id: input.id, prototypeId: bundle.value.document.id, ...(input.parentRevisionId === undefined ? {} : { parentRevisionId: input.parentRevisionId }), createdAt, author: input.author, document: bundle.value.document, documentFingerprint: await sha256Fingerprint(bundle.value.document), referenceEvidenceFingerprints: bundle.value.evidence.map(item => item.fingerprint), designSpecFingerprint: await sha256Fingerprint(bundle.value.designSpec), changeSummary: input.changeSummary } } }
export function validatePrototypeRevision(value: unknown): ValidationResult<PrototypeRevisionV1> { if (!object(value) || !keys(value, ['v', 'id', 'prototypeId', 'parentRevisionId', 'createdAt', 'author', 'document', 'documentFingerprint', 'referenceEvidenceFingerprints', 'designSpecFingerprint', 'changeSummary']) || value.v !== 1 || !id(value.id) || !id(value.prototypeId) || (value.parentRevisionId !== undefined && !id(value.parentRevisionId)) || !isIsoDate(value.createdAt) || !['agent', 'user'].includes(String(value.author)) || !text(value.documentFingerprint, 64) || !hash.test(value.documentFingerprint) || !strings(value.referenceEvidenceFingerprints, MAX_REFERENCE_EVIDENCE, 64) || value.referenceEvidenceFingerprints.length === 0 || !value.referenceEvidenceFingerprints.every(item => hash.test(item)) || !text(value.designSpecFingerprint, 64) || !hash.test(value.designSpecFingerprint) || !text(value.changeSummary, 600)) return fail('原型版本格式无效。'); const document = validatePrototypeDocument(value.document); if (!document.ok || document.value.id !== value.prototypeId) return fail('原型版本必须保存同一个已校验原型文档。'); return { ok: true, value: value as unknown as PrototypeRevisionV1 } }
export async function verifyTrustedRevision(revision: unknown, designSpec: unknown, evidence: readonly unknown[]): Promise<boolean> { const checked = validatePrototypeRevision(revision); if (!checked.ok) return false; const bundle = validatePrototypeBundle({ evidence: [...evidence], designSpec, document: checked.value.document }); if (!bundle.ok || !(await Promise.all(bundle.value.evidence.map(verifyReferenceEvidenceFingerprint))).every(Boolean)) return false; return checked.value.documentFingerprint === await sha256Fingerprint(bundle.value.document) && checked.value.designSpecFingerprint === await sha256Fingerprint(bundle.value.designSpec) && canonicalJson(checked.value.referenceEvidenceFingerprints) === canonicalJson(bundle.value.evidence.map(item => item.fingerprint)) }
