import assert from 'node:assert/strict'
import { readFile } from 'node:fs/promises'
import test from 'node:test'

test('Skill settings keeps card actions in the header and safely exposes bulk and delete actions', async () => {
  const [section, css, enable, update, host, folderUpload] = await Promise.all([
    readFile(new URL('../src/client/section.tsx', import.meta.url), 'utf8'),
    readFile(new URL('../src/client/section.module.css', import.meta.url), 'utf8'),
    readFile(new URL('../src/client/enable-installed-skill.mjs', import.meta.url), 'utf8'),
    readFile(new URL('../src/client/update-skill-modes.mjs', import.meta.url), 'utf8'),
    readFile(new URL('../src/index.ts', import.meta.url), 'utf8'),
    readFile(new URL('../src/client/folder-upload.mjs', import.meta.url), 'utf8'),
  ])

  assert.doesNotMatch(section, /radiogroup|role="radio"/)
  assert.match(section, /className=\{css\.cardHeader\}/)
  assert.match(section, /className=\{css\.cardActions\}/)
  assert.match(section, /\{t\('enabled'\)\}/)
  assert.match(section, /\{t\('disabled'\)\}/)
  assert.match(section, /\{t\('more'\)\}/)
  assert.match(section, /role="menu"/)
  assert.match(section, /role="menuitem"/)
  assert.match(section, /api\/settings\.skill\.delete/)
  assert.match(section, /api\/settings\.skill\.catalog/)
  assert.match(section, /refreshAfterDeletedSkill\(api, NS, view\.revision\)/)
  assert.match(section, /文件夹已删除，但菜单刷新失败/)
  assert.match(section, /pointerdown/)
  assert.match(section, /event\.key === 'Escape'/)
  assert.match(section, /\{t\('enableAll'\)\}/)
  assert.match(section, /\{t\('disableAll'\)\}/)
  assert.match(section, /type="checkbox"/)
  assert.match(section, /skill\.stateEditable \? <label/)
  assert.match(section, /!skill\.deletable \? null : <button/)
  assert.match(section, /className=\{css\.skillTags\}/)
  assert.match(section, /\$\{css\.statusTag\}/)
  assert.match(section, /tagSystemDefault/)
  assert.match(section, /tagAuthorModel/)
  assert.match(section, /tagAuthorUser/)
  assert.match(section, /className=\{css\.skillDescription\}/)
  assert.match(section, /selectedCount === 0/)
  assert.match(section, /modesForSelection\(visibleSkills, selected, mode\)/)
  assert.match(section, /\{t\('manualAll'\)\}/)
  assert.doesNotMatch(section, /<select|<option/)
  assert.match(section, /className=\{css\.originFilterTrigger\} type="button" aria-haspopup="listbox" aria-expanded=\{originMenuOpen\}/)
  assert.match(section, /className=\{css\.originFilterMenu\} role="listbox"/)
  assert.match(section, /className=\{css\.originFilterOption\} type="button" role="option" aria-selected=\{originFilter === 'all'\}/)
  assert.match(section, /data-origin-filter-menu/)
  assert.match(section, /setSelected\(new Set\(\)\)/)
  assert.match(section, /updateSkillModes\(api, NS, modes, view\.revision\)/)
  assert.match(update, /patch: \{ modes \}/)
  assert.match(update, /expectedRevision: revision/)
  assert.match(update, /settings-conflict/)
  assert.match(css, /\.cardHeader \{[\s\S]*?display: flex;[\s\S]*?justify-content: space-between;/)
  assert.match(css, /\.cardActions \{[\s\S]*?position: relative;[\s\S]*?flex: 0 0 auto;/)
  assert.match(css, /\.moreMenu \{[\s\S]*?position: absolute;/)
  assert.match(css, /\.moreMenu \.deleteButton \{ color: var\(--dsw-alias-label-danger\); \}/)
  assert.match(css, /\.secondaryButton \{[\s\S]*?height: 28px;[\s\S]*?border-radius: 14px;/)
  assert.match(css, /\.toolbar \{ display: flex; flex-wrap: wrap; align-items: center; gap: 6px; min-width: 0; \}/)
  assert.match(css, /\.toolbarActions \{[\s\S]*?flex: 1 1 auto;[\s\S]*?flex-wrap: wrap;/)
  assert.match(css, /\.originFilter \{[\s\S]*?position: relative;[\s\S]*?margin-left: auto;/)
  assert.match(css, /\.originFilterTrigger \{[\s\S]*?height: 28px;[\s\S]*?border-radius: 14px;/)
  assert.match(css, /\.originFilterMenu \{[\s\S]*?position: absolute;[\s\S]*?right: 0;[\s\S]*?box-shadow: var\(--dsw-shadow-lv3\);/)
  assert.match(css, /\.originFilterOption:hover, \.originFilterOption\[aria-selected='true'\] \{[\s\S]*?background: var\(--dsw-alias-interactive-bg-hover\);/)
  assert.match(css, /\.skillTitle \{[\s\S]*?display: flex;[\s\S]*?min-width: 0;/)
  assert.match(css, /\.selectionControl input \{[\s\S]*?width: 16px;[\s\S]*?height: 16px;/)
  assert.match(css, /\.skillTags \{[\s\S]*?flex-wrap: wrap;/)
  assert.match(css, /\.skillTag \{[\s\S]*?height: 20px;/)
  assert.match(css, /\.cardActions \{[\s\S]*?align-self: center;/)
  assert.match(section, /className=\{css\.intro\}/)
  assert.match(section, /api\/settings\.skill\.install/)
  assert.match(section, /getAsFileSystemHandle/)
  assert.doesNotMatch(section, /showDirectoryPicker/)
  assert.match(section, /webkitdirectory/)
  assert.match(folderUpload, /webkitRelativePath/)
  assert.match(enable, /expectedRevision: revision/)
  assert.match(enable, /settings-conflict/)
  assert.match(host, /path: '\/api\/settings\.skill\.delete'/)
  assert.match(host, /ctx\.skills\.listSource\(\{ cwd \}\)[\s\S]*?deletionTargetForSkill\(live, root, installedNames\)[\s\S]*?deleteDiscoveredSkill\(live, root, installedNames\)[\s\S]*?invalidateInvocationPolicy\(\)[\s\S]*?waitForRemovedSkill/)
  assert.match(host, /它可能来自其他来源/)
  assert.match(host, /技能删除仅允许本机同源请求/)
  assert.match(host, /path: '\/api\/settings\.skill\.catalog'/)
  assert.match(host, /listSource\(\{ cwd \}\)/)
  assert.match(host, /deletable: await deletionTargetForSkill\(skill, root, installedNames\) !== undefined/)
  assert.match(host, /系统内置技能 \/\$\{name\} 不能删除/)
  assert.match(host, /项目技能 \/\$\{name\} 不能在此处删除/)
  assert.match(section, /typeof \(item as \{ deletable\?: unknown \}\)\.deletable === 'boolean'/)
  assert.match(section, /deletable: catalogEntry\?\.deletable === true/)
  assert.match(host, /prepareSkillInstall[\s\S]*?listSource\(\{ cwd \}\)[\s\S]*?writePreparedSkill/)
  assert.match(host, /assertStateModes\(next\.modes, systemNames, legacyModes\)/)
  assert.match(host, /legacyModes\[name\] = mode/)
  assert.match(host, /resolve\(skill\) \{ return stateEditable\(skill\) \? invocationForMode/)
})
