import assert from 'node:assert/strict'
import { readFile } from 'node:fs/promises'
import test from 'node:test'

test('Prototype Studio writes are limited to its authorized extension page', async () => {
  const source = await readFile(new URL('../background.ts', import.meta.url), 'utf8')
  assert.match(source, /const PROTOTYPE_STUDIO_RESTORE_PATH = '\/api\/prototype-studio\/restore'/)
  assert.match(source, /const PROTOTYPE_STUDIO_RECOVER_PATH = '\/api\/prototype-studio\/recover'/)
  assert.match(source, /request\.type === 'prototype-studio-recover\/v1'/)
  assert.match(source, /isPrototypeStudioSender\(sender, request\.projectId, request\.referenceId\)/)
  assert.match(source, /type: 'sign-prototype-recovery'/)
  assert.match(source, /requestPrototypeRecoverySignature/)
  assert.match(source, /prototype_recovery_signed/)
  assert.doesNotMatch(source, /explicitUserAction: true/)
  assert.doesNotMatch(source, /knowledgeProxyConfig\?\.token.*recover/s)
  assert.match(source, /recoveredPrototypeSnapshot/)
  assert.match(source, /await rememberPrototypeStudio\(authorization\)/)
  assert.match(source, /const PROTOTYPE_STUDIO_REVISION_PREVIEW_PATH = '\/api\/prototype-studio\/revision-preview'/)
  assert.match(source, /request\.type === 'prototype-studio-revision-preview\/v1'/)
  assert.match(source, /targetRevisionId: request\.targetRevisionId/)
  assert.match(source, /request\.type === 'prototype-studio-restore\/v1'/)
  assert.match(source, /request\.type === 'prototype-studio-confirm-design\/v1'/)
  assert.match(source, /const PROTOTYPE_STUDIO_REOPEN_DESIGN_PATH = '\/api\/prototype-studio\/reopen-design'/)
  assert.match(source, /const PROTOTYPE_STUDIO_CONFIRM_BRIEF_PATH = '\/api\/prototype-studio\/confirm-brief'/)
  assert.match(source, /const PROTOTYPE_STUDIO_BEGIN_BRIEF_SUGGESTION_PATH = '\/api\/prototype-studio\/begin-brief-suggestion'/)
  assert.match(source, /request\.type === 'prototype-studio-confirm-brief\/v1'/)
  assert.match(source, /request\.type === 'prototype-studio-suggest-brief\/v1'/)
  assert.match(source, /prototypeHostRequest\(authorization, PROTOTYPE_STUDIO_BEGIN_BRIEF_SUGGESTION_PATH/)
  assert.match(source, /type: 'prototype-studio-brief-suggestion-forward\/v1'/)
  assert.match(source, /产品需求清单没有完成安全保存和同内容回读/)
  assert.match(source, /request\.type === 'prototype-studio-reopen-design\/v1'/)
  assert.match(source, /keys\.length !== 2/)
  assert.match(source, /prototypeHostRequest\(authorization, PROTOTYPE_STUDIO_REOPEN_DESIGN_PATH, \{\}\)/)
  assert.match(source, /request\.type === 'prototype-studio-create-variant\/v1'/)
  assert.match(source, /createPrototypeVariant\(authorization, sender\.tab!\.windowId\)/)
  assert.match(source, /verifyReferenceEvidenceFingerprint\(checked\.value\)/)
  assert.match(source, /const hostEvidence = sourceEvidence\.map\(item => \{ const \{ screenshotDataUrl: _screenshot, \.\.\.safe \} = item; return safe \}\)/)
  assert.match(source, /prototypeHostRequest\(authorization, PROTOTYPE_STUDIO_OPEN_PATH, \{ sessionId: authorization\.sessionId, evidence: hostEvidence \}\)/)
  assert.match(source, /snapshot\.designConfirmed !== true/)
  assert.match(source, /isPrototypeStudioSender\(sender, request\.projectId\)/)
  assert.match(source, /prototypeStudioAuthorization\(request\.projectId\)/)
  assert.match(source, /targetRevisionId: request\.targetRevisionId, expectedCurrentRevisionId: request\.expectedCurrentRevisionId/)
  assert.match(source, /PROTOTYPE_STUDIO_BEGIN_GENERATION_PATH = '\/api\/prototype-studio\/begin-generation'/)
  assert.match(source, /PROTOTYPE_STUDIO_CANCEL_GENERATION_PATH = '\/api\/prototype-studio\/cancel-generation'/)
  assert.match(source, /request\.type === 'prototype-studio-cancel-generation\/v1'/)
  assert.match(source, /request\.type === 'prototype-studio-prompt\/v1'.*request\.requestId/s)
  assert.match(source, /prototypeHostRequest\(authorization, PROTOTYPE_STUDIO_BEGIN_GENERATION_PATH/)
  assert.match(source, /prototypeHostRequest\(authorization, PROTOTYPE_STUDIO_CANCEL_GENERATION_PATH/)
  assert.match(source, /原型授权已过期，请重新提取参考网页。/)
  assert.match(source, /import \{ retainedPrototypeReferences \} from '\.\.\/src\/prototype-reference-storage'/)
  assert.match(source, /const retained = retainedPrototypeReferences\(references\)/)
})

test('brief suggestions are registered before forwarding to the bound Harness conversation', async () => {
  const source = await readFile(new URL('../background.ts', import.meta.url), 'utf8')
  const handler = source.slice(source.indexOf("if (request.type === 'prototype-studio-suggest-brief/v1')"), source.indexOf("if (request.type === 'prototype-studio-prompt/v1')"))
  const begin = handler.indexOf('PROTOTYPE_STUDIO_BEGIN_BRIEF_SUGGESTION_PATH')
  const forward = handler.indexOf("type: 'prototype-studio-brief-suggestion-forward/v1'")
  assert.ok(begin >= 0 && forward > begin)
  assert.match(handler, /snapshot\.designConfirmed !== true/)
  assert.match(handler, /snapshot\.generationAttempt !== undefined/)
  assert.match(handler, /projectId: authorization\.projectId, sessionId: authorization\.sessionId, requestId: request\.requestId/)
})

test('Native Host gives the Harness process only a public recovery key', async () => {
  const source = await readFile(new URL('../../../native-server/src/harness-process.mjs', import.meta.url), 'utf8')
  assert.match(source, /DSH_PROTOTYPE_RECOVERY_PUBLIC_KEY: this\.prototypeRecoveryPublicKey/)
  assert.match(source, /DSH_PROTOTYPE_RECOVERY_RUN_ID: this\.prototypeRecoveryRunId/)
  assert.doesNotMatch(source, /DSH_PROTOTYPE_RECOVERY_TOKEN/)
  assert.doesNotMatch(source, /privateKey/)
})

test('Prototype Studio begins before forwarding and cancels a failed forward', async () => {
  const source = await readFile(new URL('../background.ts', import.meta.url), 'utf8')
  const promptHandler = source.slice(source.indexOf("if (request.type === 'prototype-studio-prompt/v1')"), source.indexOf("if (request.type === 'save-browser-target-settings')"))
  const begin = promptHandler.indexOf('PROTOTYPE_STUDIO_BEGIN_GENERATION_PATH')
  const forward = promptHandler.indexOf("type: 'prototype-studio-prompt-forward/v1'")
  const cancel = promptHandler.indexOf('PROTOTYPE_STUDIO_CANCEL_GENERATION_PATH')
  assert.ok(begin >= 0 && forward > begin && cancel > forward)
  assert.match(promptHandler, /requestId: request\.requestId, expectedRevisionId: expectedRevisionId \?\? null/)
  assert.match(promptHandler, /prompt: request\.prompt/)
  assert.match(promptHandler, /首次生成前请先保存并确认产品需求清单/)
  assert.match(promptHandler, /briefChanged && expectedRevisionId === undefined/)
  assert.match(promptHandler, /briefChanged && selection !== undefined/)
  assert.match(promptHandler, /productBrief: generationBrief/)
  assert.match(promptHandler, /未能将本次原型生成请求交给 Harness，已取消。/)
})
