import { PROTOTYPE_ICON_PATHS, PROTOTYPE_NODE_TYPES, prototypeDesignTokens, validatePrototypeBundle } from '../../../../packages/harness-ui-prototype-studio/src/prototype-document'

/** Opaque-origin iframe (`allow-scripts` but no `allow-same-origin`), with one fixed product-owned renderer. */
export const PROTOTYPE_SANDBOX_SCHEMA = 'prototype-document/v1' as const
export type SandboxPreviewMode = 'interact' | 'select'

const id = /^[a-z][a-z0-9_-]{0,79}$/
const noncePattern = /^[A-Za-z0-9_-]{16,128}$/
const nodeTypes = new Set<string>([...PROTOTYPE_NODE_TYPES, 'table-row', 'list-item', 'tab', 'navigation-item', 'breadcrumb-item'])
const ownKeys = (value: object, expected: readonly string[]): boolean => { const keys = Object.keys(value); return keys.length === expected.length && keys.every(key => expected.includes(key)) }
const object = (value: unknown): value is Record<string, unknown> => typeof value === 'object' && value !== null && !Array.isArray(value)

function safeJson(value: unknown): string {
  return (JSON.stringify(value) ?? 'null').replace(/</g, '\\u003c').replace(/>/g, '\\u003e').replace(/&/g, '\\u0026').replace(/\u2028/g, '\\u2028').replace(/\u2029/g, '\\u2029')
}

function errorDoc(message: string): string { return `<!doctype html><meta charset="utf-8"><p role="alert">${message.replace(/[<&>]/g, '')}</p>` }

const SANDBOX_CSS = `
html,body{margin:0;min-height:100%;font:var(--body-weight) var(--body)/var(--body-line) var(--font),sans-serif;letter-spacing:var(--letter);color:var(--text);background:var(--page)}*{box-sizing:border-box}button,input,textarea,select{font:inherit}.screen-announcement{position:fixed;width:1px;height:1px;overflow:hidden;clip-path:inset(50%);white-space:nowrap}
.shell-frame{display:grid;min-height:100vh}.shell-frame.sidebar{grid-template-columns:220px minmax(0,1fr)}.shell-frame.top{grid-template-rows:auto minmax(0,1fr)}.navigation{z-index:1;display:flex;gap:var(--space-medium);border-color:var(--border);background:var(--surface)}.navigation>strong{padding:var(--space-medium)}.navigation>div{display:flex;gap:var(--space-small)}.navigation button{min-height:var(--control);border:0;border-radius:var(--radius-small);padding:var(--space-small) var(--space-medium);color:var(--muted);background:transparent;text-align:left;cursor:pointer}.navigation button.active{color:var(--primary);background:color-mix(in srgb,var(--primary) 9%,transparent);font-weight:650}.sidebar .navigation{position:sticky;top:0;flex-direction:column;align-self:start;min-height:100vh;border-right:var(--border-width) solid var(--border)}.sidebar .navigation>div{flex-direction:column;padding:0 var(--space-small)}.top .navigation{align-items:center;justify-content:space-between;border-bottom:var(--border-width) solid var(--border)}.top .navigation>div{overflow-x:auto;padding:var(--space-small)}.canvas{display:grid;gap:var(--space-medium);max-width:var(--content);width:100%;margin:auto;padding:var(--space-large)}.node{cursor:default}[data-preview-mode=select] .node,[data-preview-mode=select] [data-prototype-element-id]{cursor:crosshair}[data-prototype-selected=true]{position:relative;outline:2px solid var(--primary)!important;outline-offset:2px}
.text-heading{margin:0;font-size:var(--heading-size);font-weight:var(--heading);line-height:var(--heading-line)}.text-body{margin:0;color:var(--text)}.text-caption{margin:0;color:var(--muted);font-size:var(--caption)}
.icon-node{display:inline-grid;width:var(--icon-size);height:var(--icon-size);place-items:center;color:currentColor}.icon-node svg{display:block;width:100%;height:100%}
.button{min-height:var(--control);width:max-content;border:var(--border-width) solid transparent;border-radius:var(--radius-small);padding:var(--space-small) var(--space-medium);color:var(--on-primary);background-color:var(--primary);background-image:var(--gradient);font-weight:650;cursor:pointer;transition:all var(--duration) var(--easing)}.button:hover:not(:disabled){filter:brightness(.97)}.button.secondary{border-color:var(--border);color:var(--text);background:var(--surface);background-image:none}.button.danger{color:var(--on-danger);background:var(--danger);background-image:none}.button:disabled{cursor:not-allowed;filter:none;opacity:.5}
.card,.list,.tabs{display:grid;gap:var(--space-medium);border:var(--border-width) solid var(--border);border-radius:var(--radius);padding:var(--space-medium);background:var(--surface);box-shadow:var(--surface-shadow)}.card h3,.list h3,.tabs h3{margin:0}
.input{display:grid;gap:var(--space-small);font-weight:600}.input input,.input textarea,.input select{min-height:var(--input);border:var(--border-width) solid var(--border);border-radius:var(--radius-small);padding:var(--space-small);color:var(--text);background:var(--surface)}.input textarea{min-height:calc(var(--input)*2.4);resize:vertical}.input input[type=checkbox]{min-height:auto;width:18px;height:18px}.input .required{margin-left:3px;color:var(--danger)}.input.invalid input,.input.invalid textarea,.input.invalid select{border-color:var(--danger)}.input-error{color:var(--danger);font-size:var(--caption);font-weight:500}
.group{display:flex;min-width:0;gap:var(--space-medium)}.group.column{flex-direction:column}.group.row{flex-flow:row wrap}.group.grid-2,.group.grid-3{display:grid}.group.grid-2{grid-template-columns:repeat(2,minmax(0,1fr))}.group.grid-3{grid-template-columns:repeat(3,minmax(0,1fr))}
.metric{display:grid;min-width:0;gap:var(--space-small);border:var(--border-width) solid var(--border);border-radius:var(--radius);padding:var(--space-medium);background:var(--surface);box-shadow:var(--surface-shadow)}.metric small,.metric span{color:var(--muted);font-size:var(--caption)}.metric strong{font-size:calc(var(--heading-size)*.8)}
.badge{display:inline-flex;width:max-content;border-radius:999px;padding:3px 8px;color:var(--muted);background:var(--page);font-size:var(--caption)}.badge.primary{color:var(--primary)}.badge.positive{color:var(--positive);background:color-mix(in srgb,var(--positive) 10%,transparent)}.badge.warning{color:var(--warning);background:color-mix(in srgb,var(--warning) 10%,transparent)}.badge.danger{color:var(--danger);background:color-mix(in srgb,var(--danger) 10%,transparent)}
.alert{display:grid;gap:3px;border:var(--border-width) solid var(--border);border-left:4px solid var(--info);border-radius:var(--radius-small);padding:var(--space-small) var(--space-medium);background:var(--surface)}.alert span{color:var(--muted);font-size:var(--caption)}.alert.positive{border-left-color:var(--positive)}.alert.warning{border-left-color:var(--warning)}.alert.danger{border-left-color:var(--danger)}
.progress{display:grid;gap:var(--space-small)}.progress header{display:flex;justify-content:space-between}.progress header span{color:var(--muted);font-size:var(--caption)}.progress>div{height:8px;overflow:hidden;border-radius:999px;background:var(--border)}.progress i{display:block;height:100%;border-radius:inherit;background:var(--primary)}.progress i.positive{background:var(--positive)}.progress i.warning{background:var(--warning)}.progress i.danger{background:var(--danger)}
.chart{display:grid;min-width:0;gap:var(--space-medium);margin:0;border:var(--border-width) solid var(--border);border-radius:var(--radius);padding:var(--space-medium);background:var(--surface);box-shadow:var(--surface-shadow)}.chart>div{display:flex;gap:var(--space-small);align-items:end;min-height:180px}.chart>div>span{display:grid;flex:1;grid-template-rows:auto 1fr auto;gap:5px;align-items:end;height:180px;text-align:center}.chart small{overflow:hidden;color:var(--muted);text-overflow:ellipsis;white-space:nowrap;font-size:var(--caption)}.chart i{display:block;min-height:4px;border-radius:var(--radius-small) var(--radius-small) 2px 2px;background:var(--primary)}.chart b{font-size:var(--caption)}
.table{min-width:0;overflow:hidden;border:var(--border-width) solid var(--border);border-radius:var(--radius);background:var(--surface);box-shadow:var(--surface-shadow)}.table h3{margin:0;padding:var(--space-medium);border-bottom:var(--border-width) solid var(--border)}.table>div{overflow:auto}.table table{width:100%;border-collapse:collapse}.table th,.table td{border-bottom:var(--border-width) solid var(--border);padding:var(--space-small) var(--space-medium);text-align:left;white-space:nowrap}.table th{color:var(--muted);background:var(--page);font-size:var(--caption)}.table tbody tr:last-child td{border-bottom:0}.table tr.actionable{cursor:pointer}.table tr.actionable:hover{background:var(--page)}
.list-item{display:grid;width:100%;border:0;border-bottom:var(--border-width) solid var(--border);padding:var(--space-small) 0;color:var(--text);background:transparent;text-align:left;cursor:pointer}.list-item:last-child{border-bottom:0}.list-item small{color:var(--muted)}.tabs-nav{display:flex;gap:var(--space-small);border-bottom:var(--border-width) solid var(--border)}.tabs-nav button{border:0;border-bottom:2px solid transparent;padding:var(--space-small) var(--space-medium);color:var(--muted);background:transparent;cursor:pointer}.tabs-nav button.active{border-bottom-color:var(--primary);color:var(--primary);font-weight:650}.breadcrumb{display:flex;flex-wrap:wrap;gap:6px;align-items:center;color:var(--muted);font-size:var(--caption)}.breadcrumb button{border:0;padding:3px 0;color:var(--primary);background:transparent;cursor:pointer}.breadcrumb b{color:var(--text)}.empty-state{display:grid;justify-items:center;gap:var(--space-small);border:var(--border-width) dashed var(--border);border-radius:var(--radius);padding:calc(var(--space-large)*1.5);background:var(--surface);text-align:center}.empty-state>i{width:44px;height:44px;border-radius:50%;background:color-mix(in srgb,var(--primary) 10%,transparent)}.empty-state h3,.empty-state p{margin:0}.empty-state p{max-width:420px;color:var(--muted)}.pagination{display:flex;flex-wrap:wrap;gap:6px;justify-content:flex-end}.pagination button{min-width:34px;min-height:34px;border:var(--border-width) solid var(--border);border-radius:var(--radius-small);padding:4px 8px;color:var(--text);background:var(--surface);cursor:pointer}.pagination button.active{border-color:var(--primary);color:var(--on-primary);background:var(--primary)}.pagination button:disabled{cursor:not-allowed;opacity:.45}
.backdrop{position:fixed;z-index:5;inset:0;display:grid;place-items:center;padding:var(--space-large);background:#0f172a66}.modal{display:grid;gap:var(--space-medium);width:min(480px,100%);max-height:calc(100vh - 40px);overflow:auto;border-radius:var(--radius-large);padding:var(--space-medium);color:var(--text);background:var(--elevated);box-shadow:var(--elevated-shadow)}.modal-head{display:flex;align-items:center;justify-content:space-between}.modal-close{border:0;border-radius:var(--radius-small);padding:6px 9px;color:var(--muted);background:var(--page);cursor:pointer}.backdrop.drawer-left{place-items:stretch start;padding:0}.backdrop.drawer-right{place-items:stretch end;padding:0}.modal.drawer-left,.modal.drawer-right{width:min(520px,90vw);max-height:100vh;min-height:100vh;border-radius:0}
button:focus-visible,input:focus-visible,textarea:focus-visible,select:focus-visible,[tabindex]:focus-visible{outline:var(--focus-width) var(--focus-style) var(--focus-color);outline-offset:var(--focus-offset)}@media(max-width:760px){.group.grid-2,.group.grid-3{grid-template-columns:minmax(0,1fr)}.shell-frame.sidebar{grid-template-columns:1fr;grid-template-rows:auto minmax(0,1fr)}.sidebar .navigation{position:static;min-height:0;flex-direction:row;align-items:center;justify-content:space-between;overflow-x:auto;border-right:0;border-bottom:var(--border-width) solid var(--border)}.sidebar .navigation>div{flex-direction:row;padding:var(--space-small)}}`

function fixedRuntime(documentJson: string, nonceJson: string, iconPathsJson: string): string {
  return `(()=>{
const doc=${documentJson};const nonce=${nonceJson};const iconPaths=${iconPathsJson};const schema='${PROTOTYPE_SANDBOX_SCHEMA}';const root=document.getElementById('root');const announcement=document.getElementById('screen-announcement');let mode='interact';let selected;let closeButton;let focusOriginId;let restoreFocusId;let state={screenId:doc.initialScreenId,open:[],values:{},stateValues:Object.fromEntries((doc.stateVariables||[]).map(variable=>[variable.id,variable.initialValue])),tabs:{},validationErrors:[]};
const el=(tag,className)=>{const item=document.createElement(tag);if(className)item.className=className;return item};const labelOf=node=>node.text||node.title||node.label||node.id;
const stateVariable=stateId=>(doc.stateVariables||[]).find(variable=>variable.id===stateId);const setState=(stateId,value)=>{const variable=stateVariable(stateId);if(!variable||typeof value!=='string'||!variable.allowedValues.includes(value))return false;state.stateValues[stateId]=value;return true};const visible=node=>!node.visibleWhen||state.stateValues[node.visibleWhen.stateId]===node.visibleWhen.equals;const submits=action=>action&&(action.type==='submit-success'||action.type==='sequence'&&action.actions.some(submits));const requiredInputs=nodes=>nodes.flatMap(node=>!visible(node)?[]:node.type==='input'&&(node.required||node.inputType==='email'||node.inputType==='number')?[node]:node.type==='modal'?state.open.includes(node.id)?requiredInputs(node.children):[]:node.type==='card'||node.type==='group'?requiredInputs(node.children):node.type==='tabs'?requiredInputs((node.tabs.find(tab=>tab.id===(state.tabs[node.id]||node.tabs[0].id))||{children:[]}).children):[]);const inputValue=node=>{if(node.inputType==='checkbox')return node.required!==true||state.values[node.id]===true;const value=String(node.bindStateId===undefined?state.values[node.id]??node.value??'':state.stateValues[node.bindStateId]??node.value??'').trim();if(!value)return node.required!==true;if(node.inputType==='email')return /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(value);if(node.inputType==='number')return Number.isFinite(Number(value));return true};
const mark=()=>{document.body.dataset.previewMode=mode;root.querySelectorAll('[data-prototype-element-id]').forEach(item=>item.dataset.prototypeSelected=String(mode==='select'&&item.dataset.prototypeElementId===selected))};
const select=(node,type=node.type,label=labelOf(node))=>{selected=node.id;mark();parent.postMessage({v:1,type:'prototype-selection/v1',schema,nonce,selection:{elementId:node.id,type,label}},'*')};
const opensModal=action=>action&&(action.type==='open-modal'||action.type==='sequence'&&action.actions.some(opensModal));const applyAction=action=>{if(action.type==='sequence'){action.actions.forEach(applyAction);return}if(action.type==='navigate'||action.type==='submit-success'){state.screenId=action.targetScreenId;state.open=[];state.validationErrors=[]}if(action.type==='open-modal'&&!state.open.includes(action.targetId))state.open.push(action.targetId);if(action.type==='close-modal')state.open=state.open.filter(id=>id!==action.targetId);if(action.type==='set-value')state.values[action.targetId]=action.value;if(action.type==='set-state')setState(action.targetId,action.value);if(action.type==='toggle')state.values[action.targetId]=!state.values[action.targetId];if(action.type==='set-tab')state.tabs[action.targetId]=action.value};const act=action=>{if(!action)return;if(submits(action)){const screen=doc.screens.find(item=>item.id===state.screenId)||doc.screens[0];state.validationErrors=requiredInputs(screen.nodes).filter(node=>!inputValue(node)).map(node=>node.id);if(state.validationErrors.length){render();return}}applyAction(action);render()};
const activate=(event,node,action,type,label)=>{event.stopPropagation();if(mode==='select')select(node,type,label);else{if(opensModal(action))focusOriginId=node.id;act(action)}};
const wrap=(node,tag,className)=>{const item=el(tag,className+' node');item.dataset.prototypeElementId=node.id;if(mode==='select'){item.tabIndex=0;if(selected===node.id)item.dataset.prototypeSelected='true'}item.onclick=event=>{event.stopPropagation();if(mode==='select')select(node)};item.onkeydown=event=>{if(mode==='select'&&(event.key==='Enter'||event.key===' ')){event.preventDefault();event.stopPropagation();select(node)}};return item};
const renderNode=(node,asModal=false)=>{if(!visible(node)||(node.type==='modal'&&!asModal))return null;
if(node.type==='text'){const item=wrap(node,'p','text-'+(node.tone||'body'));item.textContent=node.text;return item}
if(node.type==='icon'){const item=wrap(node,'span','icon-node');const svg=document.createElementNS('http://www.w3.org/2000/svg','svg');svg.setAttribute('viewBox','0 0 24 24');svg.setAttribute('fill','none');svg.setAttribute('stroke','currentColor');svg.setAttribute('stroke-width','2');svg.setAttribute('stroke-linecap','round');svg.setAttribute('stroke-linejoin','round');svg.setAttribute('focusable','false');const path=document.createElementNS('http://www.w3.org/2000/svg','path');path.setAttribute('d',iconPaths[node.name]);svg.append(path);if(node.label){svg.setAttribute('role','img');svg.setAttribute('aria-label',node.label)}else svg.setAttribute('aria-hidden','true');item.append(svg);return item}
if(node.type==='button'){const item=wrap(node,'button','button '+(node.variant||'primary'));item.type='button';item.disabled=node.disabled===true&&mode!=='select';if(node.disabled===true)item.setAttribute('aria-disabled','true');item.textContent=node.label;item.onclick=event=>activate(event,node,node.action);return item}
if(node.type==='input'){const invalid=state.validationErrors.includes(node.id);const item=wrap(node,'label','input'+(invalid?' invalid':''));const name=el('span');name.textContent=node.label;if(node.required){const required=el('em','required');required.textContent='*';required.setAttribute('aria-hidden','true');name.append(required)}let input;if(node.inputType==='textarea')input=el('textarea');else if(node.inputType==='select'){input=el('select');const empty=el('option');empty.value='';empty.textContent=node.placeholder||'请选择';input.append(empty);node.options.forEach(option=>{const choice=el('option');choice.value=option.value;choice.textContent=option.label;input.append(choice)})}else{input=el('input');input.type=node.inputType||'text'}input.placeholder=node.placeholder||'';input.setAttribute('aria-required',String(node.required===true));if(invalid){input.setAttribute('aria-invalid','true');input.setAttribute('aria-describedby',node.id+'-error')}if(node.inputType==='checkbox')input.checked=Boolean(state.values[node.id]);else input.value=String(node.bindStateId===undefined?state.values[node.id]??node.value??'':state.stateValues[node.bindStateId]??node.value??'');input.onmousedown=event=>{if(mode==='select')event.preventDefault()};input.onkeydown=event=>{if(mode==='select')event.preventDefault()};input.onclick=event=>{event.stopPropagation();if(mode==='select'){event.preventDefault();select(node)}};const update=()=>{if(mode!=='interact'){if(node.inputType==='checkbox')input.checked=Boolean(state.values[node.id]);else input.value=String(node.bindStateId===undefined?state.values[node.id]??node.value??'':state.stateValues[node.bindStateId]??node.value??'');return}state.validationErrors=state.validationErrors.filter(id=>id!==node.id);if(node.bindStateId!==undefined){setState(node.bindStateId,input.value);render()}else state.values[node.id]=node.inputType==='checkbox'?input.checked:input.value};input.oninput=update;input.onchange=update;item.append(name,input);if(invalid){const error=el('small','input-error');error.id=node.id+'-error';error.setAttribute('role','alert');error.textContent=node.errorText||(node.inputType==='email'?'请输入有效的'+node.label:node.inputType==='number'?'请输入有效数字':'请填写'+node.label);item.append(error)}return item}
if(node.type==='card'||node.type==='group'||node.type==='modal'){const className=node.type==='modal'?'modal '+(node.placement||'dialog'):node.type==='group'?'group '+node.layout:'card';const item=wrap(node,'section',className);if(node.type==='modal'){item.setAttribute('role','dialog');item.setAttribute('aria-modal','true');item.setAttribute('aria-label',node.title);const head=el('div','modal-head');const title=el('b');title.textContent=node.title;closeButton=el('button','modal-close');closeButton.type='button';closeButton.textContent='关闭';closeButton.onclick=event=>activate(event,node,{type:'close-modal',targetId:node.id});head.append(title,closeButton);item.append(head)}else if(node.label){const title=el('h3');title.textContent=node.label;item.append(title)}node.children.forEach(child=>{const rendered=renderNode(child);if(rendered)item.append(rendered)});return item}
if(node.type==='metric'){const item=wrap(node,'article','metric '+(node.tone||'neutral'));const label=el('small');label.textContent=node.label;const value=el('strong');value.textContent=node.value;item.append(label,value);if(node.detail){const detail=el('span');detail.textContent=node.detail;item.append(detail)}return item}
if(node.type==='badge'){const item=wrap(node,'span','badge '+(node.tone||'neutral'));item.textContent=node.text;return item}
if(node.type==='alert'){const item=wrap(node,'aside','alert '+(node.tone||'info'));item.setAttribute('role','status');const title=el('b');title.textContent=node.title;item.append(title);if(node.detail){const detail=el('span');detail.textContent=node.detail;item.append(detail)}return item}
if(node.type==='progress'){const item=wrap(node,'section','progress');const head=el('header');const label=el('b');label.textContent=node.label;const detail=el('span');detail.textContent=node.detail||node.value+'%';head.append(label,detail);const track=el('div');track.setAttribute('role','progressbar');track.setAttribute('aria-label',node.label);track.setAttribute('aria-valuemin','0');track.setAttribute('aria-valuemax','100');track.setAttribute('aria-valuenow',String(node.value));const fill=el('i',node.tone||'primary');fill.style.width=node.value+'%';track.append(fill);item.append(head,track);return item}
if(node.type==='chart'){const item=wrap(node,'figure','chart');const title=el('figcaption');title.textContent=node.label;const bars=el('div');const maximum=Math.max(...node.bars.map(bar=>bar.value),1);node.bars.forEach(bar=>{const group=el('span');const label=el('small');label.textContent=bar.label;const column=el('i');column.style.height=Math.max(4,Math.round(bar.value/maximum*100))+'%';const value=el('b');value.textContent=String(bar.value);group.append(label,column,value);bars.append(group)});item.append(title,bars);return item}
if(node.type==='table'){const item=wrap(node,'section','table');if(node.label){const title=el('h3');title.textContent=node.label;item.append(title)}const hasActions=node.rows.some(row=>row.action);const tableLabel=node.label||'表格';const scroll=el('div');const table=el('table');const head=el('thead');const headRow=el('tr');node.columns.forEach(column=>{const cell=el('th');cell.setAttribute('scope','col');cell.textContent=column.label;headRow.append(cell)});if(hasActions){const cell=el('th');cell.setAttribute('scope','col');cell.textContent='操作';headRow.append(cell)}head.append(headRow);const body=el('tbody');node.rows.forEach(row=>{const line=el('tr');line.dataset.prototypeElementId=row.id;if(mode==='select')line.tabIndex=0;line.onclick=event=>{event.stopPropagation();if(mode==='select')select(row,'table-row',row.values[0]||row.id)};line.onkeydown=event=>{if(mode==='select'&&(event.key==='Enter'||event.key===' ')){event.preventDefault();event.stopPropagation();select(row,'table-row',row.values[0]||row.id)}};row.values.forEach(value=>{const cell=el('td');cell.textContent=value;line.append(cell)});if(hasActions){const cell=el('td');if(row.action){const button=el('button');button.type='button';button.textContent='打开详情';button.setAttribute('aria-label',tableLabel+'：打开 '+(row.values[0]||row.id));button.onclick=event=>activate(event,row,row.action,'table-row',row.values[0]||row.id);cell.append(button)}line.append(cell)}body.append(line)});table.append(head,body);scroll.append(table);item.append(scroll);return item}
if(node.type==='list'){const item=wrap(node,'section','list');if(node.label){const title=el('h3');title.textContent=node.label;item.append(title)}node.items.forEach(entry=>{const line=el(entry.action?'button':'div','list-item');if(entry.action)line.type='button';else if(mode==='select')line.tabIndex=0;line.dataset.prototypeElementId=entry.id;const title=el('b');title.textContent=entry.title;line.append(title);if(entry.detail){const detail=el('small');detail.textContent=entry.detail;line.append(detail)}line.onclick=event=>{event.stopPropagation();if(entry.action)activate(event,entry,entry.action,'list-item',entry.title);else if(mode==='select')select(entry,'list-item',entry.title)};line.onkeydown=event=>{if(!entry.action&&mode==='select'&&(event.key==='Enter'||event.key===' ')){event.preventDefault();select(entry,'list-item',entry.title)}};item.append(line)});return item}
if(node.type==='tabs'){const item=wrap(node,'section','tabs');if(node.label){const title=el('h3');title.textContent=node.label;item.append(title)}const nav=el('div','tabs-nav');nav.setAttribute('role','tablist');const active=state.tabs[node.id]||node.tabs[0].id;const activateTab=tab=>activate({stopPropagation(){}},tab,tab.action||{type:'set-tab',targetId:node.id,value:tab.id},'tab',tab.label);node.tabs.forEach(tab=>{const button=el('button',tab.id===active?'active':'');button.type='button';button.tabIndex=tab.id===active?0:-1;button.dataset.prototypeElementId=tab.id;button.id=node.id+'-tab-'+tab.id;button.setAttribute('role','tab');button.setAttribute('aria-controls',node.id+'-panel-'+tab.id);button.setAttribute('aria-selected',String(tab.id===active));button.textContent=tab.label;button.onclick=event=>activate(event,tab,tab.action||{type:'set-tab',targetId:node.id,value:tab.id},'tab',tab.label);button.onkeydown=event=>{if(mode==='select'){if(event.key==='Enter'||event.key===' '){event.preventDefault();select(tab,'tab',tab.label)}return}if(!['ArrowLeft','ArrowRight','Home','End'].includes(event.key))return;event.preventDefault();const current=node.tabs.findIndex(item=>item.id===tab.id);const next=event.key==='Home'?0:event.key==='End'?node.tabs.length-1:(current+(event.key==='ArrowLeft'?-1:1)+node.tabs.length)%node.tabs.length;const target=node.tabs[next];activateTab(target);requestAnimationFrame(()=>document.getElementById(node.id+'-tab-'+target.id)?.focus())};nav.append(button)});item.append(nav);const activeTab=node.tabs.find(tab=>tab.id===active);if(activeTab){const panel=el('div');panel.id=node.id+'-panel-'+activeTab.id;panel.setAttribute('role','tabpanel');panel.setAttribute('aria-labelledby',node.id+'-tab-'+activeTab.id);activeTab.children.forEach(child=>{const rendered=renderNode(child);if(rendered)panel.append(rendered)});item.append(panel)}return item}
if(node.type==='breadcrumb'){const item=wrap(node,'nav','breadcrumb');item.setAttribute('aria-label','面包屑');node.items.forEach((entry,index)=>{if(index){const slash=el('span');slash.textContent='/';slash.setAttribute('aria-hidden','true');item.append(slash)}if(entry.targetScreenId){const button=el('button');button.type='button';button.dataset.prototypeElementId=entry.id;button.textContent=entry.label;button.onclick=event=>activate(event,entry,{type:'navigate',targetScreenId:entry.targetScreenId},'breadcrumb-item',entry.label);item.append(button)}else{const current=el('b');current.dataset.prototypeElementId=entry.id;if(mode==='select')current.tabIndex=0;current.textContent=entry.label;current.onclick=event=>{event.stopPropagation();if(mode==='select')select(entry,'breadcrumb-item',entry.label)};current.onkeydown=event=>{if(mode==='select'&&(event.key==='Enter'||event.key===' ')){event.preventDefault();event.stopPropagation();select(entry,'breadcrumb-item',entry.label)}};item.append(current)}});return item}
if(node.type==='empty-state'){const item=wrap(node,'section','empty-state');const icon=el('i');icon.setAttribute('aria-hidden','true');const title=el('h3');title.textContent=node.title;item.append(icon,title);if(node.detail){const detail=el('p');detail.textContent=node.detail;item.append(detail)}if(node.action){const button=el('button','button secondary');button.type='button';button.textContent=node.actionLabel;button.onclick=event=>activate(event,node,node.action);item.append(button)}return item}
if(node.type==='pagination'){const item=wrap(node,'nav','pagination');item.setAttribute('aria-label',node.label||'分页');const current=Number(state.stateValues[node.bindStateId]||'1');const pageButton=(label,page,active=false)=>{const button=el('button',active?'active':'');button.type='button';button.textContent=label;button.disabled=page<1||page>node.pageCount;if(active)button.setAttribute('aria-current','page');button.onclick=event=>{event.stopPropagation();if(mode==='select')select(node);else if(setState(node.bindStateId,String(page)))render()};return button};item.append(pageButton('上一页',current-1));for(let page=1;page<=node.pageCount;page++)item.append(pageButton(String(page),page,page===current));item.append(pageButton('下一页',current+1));return item}return null};
const collectModals=nodes=>nodes.flatMap(node=>!visible(node)?[]:node.type==='modal'?[node]:node.type==='card'||node.type==='group'?collectModals(node.children):node.type==='tabs'?node.tabs.flatMap(tab=>collectModals(tab.children)):[]);
const audit=(requestId=null)=>requestAnimationFrame(()=>{const targets=[...root.querySelectorAll('button,input,textarea,select,[tabindex]')];const smallTargetCount=targets.filter(item=>{const rect=item.getBoundingClientRect();return rect.width>0&&rect.height>0&&(rect.width<32||rect.height<32)}).length;const clippedDialogCount=[...root.querySelectorAll('[role=dialog]')].filter(item=>{const rect=item.getBoundingClientRect();return rect.left<0||rect.top<0||rect.right>innerWidth+1||rect.bottom>innerHeight+1}).length;parent.postMessage({v:1,type:'prototype-preview-audit/v1',schema,nonce,requestId,audit:{viewportWidth:Math.round(innerWidth),horizontalOverflow:document.documentElement.scrollWidth>innerWidth+1||root.scrollWidth>innerWidth+1,smallTargetCount,clippedDialogCount}},'*')});
const render=()=>{root.replaceChildren();closeButton=undefined;const screen=doc.screens.find(item=>item.id===state.screenId)||doc.screens[0];announcement.textContent='当前页面：'+screen.title;const frame=el('div',doc.shell?'shell-frame '+doc.shell.placement:'');if(doc.shell){const navigation=el('nav','navigation');navigation.setAttribute('aria-label','产品导航');const product=el('strong');product.textContent=doc.shell.productName;const items=el('div');doc.shell.items.forEach(entry=>{const button=el('button',entry.targetScreenId===state.screenId?'active':'');button.type='button';button.dataset.prototypeElementId=entry.id;button.setAttribute('aria-current',entry.targetScreenId===state.screenId?'page':'false');button.textContent=entry.label;button.onclick=event=>activate(event,entry,{type:'navigate',targetScreenId:entry.targetScreenId},'navigation-item',entry.label);items.append(button)});navigation.append(product,items);frame.append(navigation)}const canvas=el('main','canvas');canvas.setAttribute('aria-label',screen.title);screen.nodes.forEach(node=>{const rendered=renderNode(node);if(rendered)canvas.append(rendered)});frame.append(canvas);root.append(frame);collectModals(screen.nodes).filter(node=>state.open.includes(node.id)).forEach(node=>{const backdrop=el('div','backdrop '+(node.placement||'dialog'));backdrop.onclick=event=>{if(mode==='interact'&&event.target===backdrop)act({type:'close-modal',targetId:node.id})};const rendered=renderNode(node,true);backdrop.append(rendered);root.append(backdrop)});mark();audit();if(state.validationErrors.length){const invalid=root.querySelector('[aria-invalid="true"]');if(invalid instanceof HTMLElement)invalid.focus()}else if(state.open.length)closeButton&&closeButton.focus();else if(focusOriginId){const origin=root.querySelector('[data-prototype-element-id="'+focusOriginId+'"]');if(origin instanceof HTMLElement)origin.focus();focusOriginId=undefined}};
window.addEventListener('message',event=>{const message=event.data;if(event.source!==parent||!message||typeof message!=='object')return;const keys=Object.keys(message);if(keys.length===5&&message.v===1&&message.type==='prototype-selection-sync/v1'&&message.schema===schema&&message.nonce===nonce&&(message.elementId===null||/^[a-z][a-z0-9_-]{0,79}$/.test(message.elementId))){selected=message.elementId||undefined;mark();return}if(keys.length===6&&message.v===1&&message.type==='prototype-coverage-focus/v1'&&message.schema===schema&&message.nonce===nonce&&(message.screenId===null||/^[a-z][a-z0-9_-]{0,79}$/.test(message.screenId))&&(message.elementId===null||/^[a-z][a-z0-9_-]{0,79}$/.test(message.elementId))){if(message.screenId!==null){if(!doc.screens.some(item=>item.id===message.screenId))return;state.screenId=message.screenId;state.open=[];state.validationErrors=[]}selected=message.elementId||undefined;render();requestAnimationFrame(()=>root.querySelector('[data-prototype-element-id="'+selected+'"]').focus?.());return}if(keys.length===5&&message.v===1&&message.type==='prototype-preview-mode/v1'&&message.schema===schema&&message.nonce===nonce&&(message.mode==='interact'||message.mode==='select')){restoreFocusId=document.activeElement?.closest?.('[data-prototype-element-id]')?.dataset.prototypeElementId;mode=message.mode;if(mode==='interact')selected=undefined;render();if(restoreFocusId){root.querySelector('[data-prototype-element-id="'+restoreFocusId+'"]').focus?.();restoreFocusId=undefined}return}if(keys.length===5&&message.v===1&&message.type==='prototype-preview-audit-request/v1'&&message.schema===schema&&message.nonce===nonce&&/^[a-f0-9-]{8,64}$/i.test(message.requestId))audit(message.requestId)});window.addEventListener('resize',()=>audit());window.addEventListener('keydown',event=>{if(mode==='select'&&event.key==='Escape'){event.preventDefault();selected=undefined;mark();parent.postMessage({v:1,type:'prototype-selection-clear/v1',schema,nonce},'*');return}if(!state.open.length)return;if(mode==='interact'&&event.key==='Escape'){event.preventDefault();act({type:'close-modal',targetId:state.open[state.open.length-1]});return}if(event.key!=='Tab')return;const dialogs=root.querySelectorAll('[role=dialog]');const dialog=dialogs[dialogs.length-1];if(!dialog)return;const focusable=[...dialog.querySelectorAll('button:not(:disabled),input:not(:disabled),textarea:not(:disabled),select:not(:disabled),[tabindex]:not([tabindex="-1"])')];if(!focusable.length){event.preventDefault();return}const first=focusable[0],last=focusable[focusable.length-1];if(event.shiftKey&&document.activeElement===first){event.preventDefault();last.focus()}else if(!event.shiftKey&&document.activeElement===last){event.preventDefault();first.focus()}});render();})()`
}

/** Validation is repeated here: callers cannot place unvalidated model output in srcdoc. */
export function sandboxPreviewSrcDoc(document: unknown, designSpec: unknown, evidence: readonly unknown[], nonce: string): string {
  if (!noncePattern.test(nonce)) return errorDoc('无效预览令牌。')
  const checked = validatePrototypeBundle({ document, designSpec, evidence: [...evidence] })
  if (!checked.ok) return errorDoc(`原型内容未通过安全校验：${checked.errors[0] ?? '未知错误'}`)
  const theme = prototypeDesignTokens(checked.value.designSpec)
  const variables = `--primary:${theme.primary};--on-primary:${theme.onPrimary};--info:${theme.info};--on-info:${theme.onInfo};--positive:${theme.positive};--on-positive:${theme.onPositive};--warning:${theme.warning};--on-warning:${theme.onWarning};--danger:${theme.danger};--on-danger:${theme.onDanger};--page:${theme.page};--surface:${theme.surface};--elevated:${theme.elevated};--text:${theme.text};--muted:${theme.textMuted};--border:${theme.border};--border-width:${theme.borderWidth};--border-style:${theme.borderStyle};--radius:${theme.radius};--radius-small:${theme.radiusSmall};--radius-large:${theme.radiusLarge};--control-radius:${theme.controlRadius};--font:${theme.font};--body:${theme.bodySize};--body-weight:${theme.bodyWeight};--body-line:${theme.bodyLineHeight};--heading-size:${theme.headingSize};--heading-line:${theme.headingLineHeight};--heading:${theme.headingWeight};--caption:${theme.captionSize};--letter:${theme.letterSpacing};--space-small:${theme.spaceSmall};--space-medium:${theme.spaceMedium};--space-large:${theme.spaceLarge};--section-gap:${theme.sectionGap};--content:${theme.contentWidth};--shadow:${theme.surfaceShadow};--surface-shadow:${theme.surfaceShadow};--elevated-shadow:${theme.elevatedShadow};--gradient:${theme.primaryControlGradient};--disabled-opacity:${theme.disabledOpacity};--control:${theme.controlHeight};--input:${theme.inputHeight};--icon-size:${theme.iconSize};--duration:${theme.motionDuration};--easing:${theme.motionEasing};--focus-width:${theme.focusWidth};--focus-style:${theme.focusStyle};--focus-color:${theme.focusColor};--focus-offset:${theme.focusOffset}`
  const runtimeStyles = SANDBOX_CSS.replace('@media(max-width:760px)', `@media(max-width:${theme.compactBreakpoint}px)`) + '.canvas{gap:var(--section-gap)}.button{border-radius:var(--control-radius)}.button:disabled,.input input:disabled,.input textarea:disabled,.input select:disabled{opacity:var(--disabled-opacity)}.navigation,.card,.list,.tabs,.metric,.chart,.table,.input input,.input textarea,.input select,.pagination button{border-style:var(--border-style)}'
  const script = fixedRuntime(safeJson(checked.value.document), safeJson(nonce), safeJson(PROTOTYPE_ICON_PATHS))
  return `<!doctype html><html><head><meta charset="utf-8"><meta http-equiv="Content-Security-Policy" content="default-src 'none'; base-uri 'none'; form-action 'none'; frame-ancestors 'none'; connect-src 'none'; img-src data:; style-src 'unsafe-inline'; script-src 'nonce-${nonce}'"><style>:root{${variables}}${runtimeStyles}</style></head><body><p id="screen-announcement" class="screen-announcement" role="status" aria-live="polite"></p><div id="root"></div><script nonce="${nonce}">${script}</script></body></html>`
}

export interface SandboxSelectionMessage { v: 1; type: 'prototype-selection/v1'; schema: typeof PROTOTYPE_SANDBOX_SCHEMA; nonce: string; selection: { elementId: string; type: string; label: string } }
export function isSandboxSelectionMessage(value: unknown, nonce: string): value is SandboxSelectionMessage {
  if (!object(value) || !ownKeys(value, ['v', 'type', 'schema', 'nonce', 'selection']) || value.v !== 1 || value.type !== 'prototype-selection/v1' || value.schema !== PROTOTYPE_SANDBOX_SCHEMA || value.nonce !== nonce || !object(value.selection) || !ownKeys(value.selection, ['elementId', 'type', 'label'])) return false
  return id.test(String(value.selection.elementId)) && nodeTypes.has(String(value.selection.type)) && typeof value.selection.label === 'string' && value.selection.label.length <= 2_000
}

export interface SandboxSelectionClearMessage { v: 1; type: 'prototype-selection-clear/v1'; schema: typeof PROTOTYPE_SANDBOX_SCHEMA; nonce: string }
export function isSandboxSelectionClearMessage(value: unknown, nonce: string): value is SandboxSelectionClearMessage {
  return object(value) && ownKeys(value, ['v', 'type', 'schema', 'nonce']) && value.v === 1 && value.type === 'prototype-selection-clear/v1' && value.schema === PROTOTYPE_SANDBOX_SCHEMA && value.nonce === nonce
}

export interface SandboxPreviewAuditMessage { v: 1; type: 'prototype-preview-audit/v1'; schema: typeof PROTOTYPE_SANDBOX_SCHEMA; nonce: string; requestId: string | null; audit: { viewportWidth: number; horizontalOverflow: boolean; smallTargetCount: number; clippedDialogCount: number } }
export function isSandboxPreviewAuditMessage(value: unknown, nonce: string): value is SandboxPreviewAuditMessage {
  if (!object(value) || !ownKeys(value, ['v', 'type', 'schema', 'nonce', 'requestId', 'audit']) || value.v !== 1 || value.type !== 'prototype-preview-audit/v1' || value.schema !== PROTOTYPE_SANDBOX_SCHEMA || value.nonce !== nonce || !(value.requestId === null || (typeof value.requestId === 'string' && /^[a-f0-9-]{8,64}$/i.test(value.requestId))) || !object(value.audit) || !ownKeys(value.audit, ['viewportWidth', 'horizontalOverflow', 'smallTargetCount', 'clippedDialogCount'])) return false
  return Number.isInteger(value.audit.viewportWidth) && Number(value.audit.viewportWidth) >= 200 && Number(value.audit.viewportWidth) <= 4_000
    && typeof value.audit.horizontalOverflow === 'boolean'
    && Number.isInteger(value.audit.smallTargetCount) && Number(value.audit.smallTargetCount) >= 0 && Number(value.audit.smallTargetCount) <= 500
    && Number.isInteger(value.audit.clippedDialogCount) && Number(value.audit.clippedDialogCount) >= 0 && Number(value.audit.clippedDialogCount) <= 20
}
