import assert from 'node:assert/strict'
import { readFile } from 'node:fs/promises'
import test from 'node:test'

const source = () => readFile(new URL('./sandbox-preview.ts', import.meta.url), 'utf8')

test('isolated preview validates its full bundle before making an opaque-origin, no-network srcdoc', async () => {
  const value = await source()
  assert.match(value, /validatePrototypeBundle\(\{ document, designSpec, evidence: \[\.\.\.evidence\] \}\)/)
  assert.match(value, /default-src 'none'/)
  assert.match(value, /connect-src 'none'/)
  assert.match(value, /script-src 'nonce-\$\{nonce\}'/)
  assert.match(value, /sandbox="allow-scripts"|allow-scripts/)
  assert.match(value, /role','tablist/)
  assert.match(value, /aria-modal/)
  assert.match(value, /node\.type==='group'/)
  assert.match(value, /node\.type==='metric'/)
  assert.match(value, /node\.type==='table'/)
  assert.match(value, /const hasActions=node\.rows\.some\(row=>row\.action\)/)
  assert.match(value, /cell\.textContent='操作'/)
  assert.match(value, /cell\.setAttribute\('scope','col'\)/)
  assert.match(value, /el\(entry\.action\?'button':'div','list-item'\)/)
  assert.match(value, /id="screen-announcement" class="screen-announcement" role="status" aria-live="polite"/)
  assert.match(value, /announcement\.textContent='当前页面：'\+screen\.title/)
  assert.match(value, /<div id="root"><\/div>/)
  assert.doesNotMatch(value, /<div id="root"[^>]*aria-live/)
  assert.match(value, /button\.textContent='打开详情'/)
  assert.match(value, /node\.type==='alert'/)
  assert.match(value, /node\.type==='progress'/)
  assert.match(value, /node\.type==='chart'/)
  assert.match(value, /node\.placement\|\|'dialog'/)
  assert.match(value, /node\.inputType==='select'/)
  assert.match(value, /node\.inputType==='textarea'/)
  assert.match(value, /--body-line:\$\{theme\.bodyLineHeight\}/)
  assert.match(value, /--surface-shadow:\$\{theme\.surfaceShadow\}/)
  assert.match(value, /--elevated-shadow:\$\{theme\.elevatedShadow\}/)
  assert.match(value, /--gradient:\$\{theme\.primaryControlGradient\}/)
  assert.match(value, /--duration:\$\{theme\.motionDuration\}/)
  assert.match(value, /--border-style:\$\{theme\.borderStyle\}/)
  assert.match(value, /--control-radius:\$\{theme\.controlRadius\}/)
  assert.match(value, /--section-gap:\$\{theme\.sectionGap\}/)
  assert.match(value, /--disabled-opacity:\$\{theme\.disabledOpacity\}/)
  assert.match(value, /SANDBOX_CSS\.replace\('@media\(max-width:760px\)', `@media\(max-width:\$\{theme\.compactBreakpoint\}px\)`\)/)
  assert.match(value, /border-style:var\(--border-style\)/)
  assert.match(value, /--positive:\$\{theme\.positive\}/)
  assert.match(value, /--warning:\$\{theme\.warning\}/)
  assert.match(value, /--danger:\$\{theme\.danger\}/)
  assert.match(value, /\.button\.danger\{color:var\(--on-danger\);background:var\(--danger\)/)
  assert.doesNotMatch(value, /\.button\.danger\{color:#fff;background:#c2413b/)
  assert.doesNotMatch(value, /bar\.textContent='原型|root\.append\(bar\)/)
  assert.doesNotMatch(value, /chrome\.|new Function|\beval\s*\(/)
})

test('selection bridge requires exact envelope and selection keys, bounded ids, known node types, and nonce', async () => {
  const value = await source()
  assert.match(value, /ownKeys\(value, \['v', 'type', 'schema', 'nonce', 'selection'\]\)/)
  assert.match(value, /ownKeys\(value\.selection, \['elementId', 'type', 'label'\]\)/)
  assert.match(value, /nodeTypes\.has/)
  assert.match(value, /value\.selection\.label\.length <= 2_000/)
  assert.match(value, /,'table-row',row\.values/)
  assert.match(value, /,'list-item',entry\.title/)
  assert.match(value, /,'tab',tab\.label/)
  assert.match(value, /doc\.shell/)
  assert.match(value, /navigation-item/)
  assert.match(value, /value\.nonce !== nonce/)
  assert.match(value, /prototype-selection-sync\/v1/)
  assert.match(value, /event\.source!==parent/)
  assert.match(value, /const keys=Object\.keys\(message\)/)
  assert.match(value, /keys\.length===5/)
  assert.doesNotMatch(value, /\u0000/)
})

test('fixed runtime has separate safe interact and select modes', async () => {
  const value = await source()
  assert.match(value, /export type SandboxPreviewMode = 'interact' \| 'select'/)
  assert.match(value, /let mode='interact'/)
  assert.match(value, /if\(mode==='select'\)select\(node,type,label\);else\{if\(opensModal\(action\)\)focusOriginId=node\.id;act\(action\)\}/)
  assert.match(value, /type==='prototype-preview-mode\/v1'/)
  assert.match(value, /message\.mode==='interact'\|\|message\.mode==='select'/)
  assert.match(value, /mode=message\.mode;if\(mode==='interact'\)selected=undefined;render\(\)/)
  assert.match(value, /if\(mode==='interact'&&event\.key==='Escape'/)
  assert.match(value, /if\(mode==='select'&&event\.key==='Escape'\)/)
  assert.match(value, /prototype-selection-clear\/v1/)
  assert.match(value, /isSandboxSelectionClearMessage/)
  assert.match(value, /item\.tabIndex=0/)
  assert.match(value, /mode=message\.mode;if\(mode==='interact'\)selected=undefined;render\(\)/)
  assert.match(value, /item\.disabled=node\.disabled===true&&mode!=='select'/)
  assert.match(value, /event\.key==='Enter'\|\|event\.key===' '/)
  assert.match(value, /if\(mode==='select'\)line\.tabIndex=0;line\.onclick=event=>\{event\.stopPropagation\(\);if\(mode==='select'\)select\(row,'table-row'/)
  assert.match(value, /line\.onkeydown=event=>\{if\(mode==='select'&&\(event\.key==='Enter'\|\|event\.key===' '\)\)\{event\.preventDefault\(\);event\.stopPropagation\(\);select\(row,'table-row'/)
  assert.match(value, /if\(mode==='select'\)current\.tabIndex=0;current\.textContent=entry\.label;current\.onclick=event=>\{event\.stopPropagation\(\);if\(mode==='select'\)select\(entry,'breadcrumb-item'/)
  assert.match(value, /current\.onkeydown=event=>\{if\(mode==='select'&&\(event\.key==='Enter'\|\|event\.key===' '\)\)\{event\.preventDefault\(\);event\.stopPropagation\(\);select\(entry,'breadcrumb-item'/)
  assert.match(value, /button\.tabIndex=tab\.id===active\?0:-1/)
  assert.match(value, /\['ArrowLeft','ArrowRight','Home','End'\]/)
  assert.match(value, /event\.key!=='Tab'/)
  assert.match(value, /button:not\(:disabled\),input:not\(:disabled\)/)
  assert.match(value, /if\(opensModal\(action\)\)focusOriginId=node\.id/)
  assert.match(value, /origin instanceof HTMLElement\)origin\.focus\(\)/)
})

test('fixed iframe runtime renders only declared business state and never changes it in selection mode', async () => {
  const value = await source()
  assert.match(value, /stateValues:Object\.fromEntries\(\(doc\.stateVariables\|\|\[\]\)\.map/)
  assert.match(value, /const stateVariable=stateId=>\(doc\.stateVariables\|\|\[\]\)\.find/)
  assert.match(value, /variable\.allowedValues\.includes\(value\)/)
  assert.match(value, /action\.type==='set-state'/)
  assert.match(value, /action\.type==='sequence'/)
  assert.match(value, /action\.actions\.forEach\(applyAction\)/)
  assert.match(value, /const visible=node=>!node\.visibleWhen\|\|state\.stateValues\[node\.visibleWhen\.stateId\]===node\.visibleWhen\.equals/)
  assert.match(value, /if\(!visible\(node\)\|\|\(node\.type==='modal'&&!asModal\)\)return null/)
  assert.match(value, /node\.bindStateId===undefined\?state\.values\[node\.id\]/)
  assert.match(value, /if\(mode!=='interact'\)\{if\(node\.inputType==='checkbox'\)/)
  assert.match(value, /if\(mode==='select'\)event\.preventDefault\(\)/)
})

test('preview reports bounded responsive-layout evidence to its nonce-bound parent', async () => {
  const value = await source()
  assert.match(value, /prototype-preview-audit\/v1/)
  assert.match(value, /prototype-preview-audit-request\/v1/)
  assert.match(value, /aria-invalid/)
  assert.match(value, /请输入有效的/)
  assert.match(value, /document\.documentElement\.scrollWidth>innerWidth\+1/)
  assert.match(value, /rect\.width<32\|\|rect\.height<32/)
  assert.match(value, /root\.querySelectorAll\('\[role=dialog\]'\)/)
  assert.match(value, /window\.addEventListener\('resize',\(\)=>audit\(\)\)/)
  assert.match(value, /requestId/)
  assert.match(value, /ownKeys\(value\.audit, \['viewportWidth', 'horizontalOverflow', 'smallTargetCount', 'clippedDialogCount'\]\)/)
  assert.match(value, /value\.nonce !== nonce/)
})

test('coverage focus is fixed-runtime only and rejects unknown screen ids', async () => {
  const value = await source()
  assert.match(value, /prototype-coverage-focus\/v1/)
  assert.match(value, /keys\.length===6/)
  assert.match(value, /doc\.screens\.some\(item=>item\.id===message\.screenId\)/)
  assert.match(value, /state\.screenId=message\.screenId;state\.open=\[\];state\.validationErrors=\[\]/)
})
