import assert from 'node:assert/strict'
import { readFile } from 'node:fs/promises'
import test from 'node:test'

test('prototype studio exposes a clear design-review gate and a sandboxed preview', async () => {
  const [main, styles, html, startupGuard] = await Promise.all([readFile(new URL('./main.tsx', import.meta.url), 'utf8'), readFile(new URL('./style.css', import.meta.url), 'utf8'), readFile(new URL('./index.html', import.meta.url), 'utf8'), readFile(new URL('../../public/prototype-startup-guard.js', import.meta.url), 'utf8')])
  const specificationStyles = styles.slice(styles.indexOf('.spec-block'), styles.indexOf('.review-example', styles.indexOf('.spec-block')))
  const tweakStyles = styles.slice(styles.indexOf('.default-confirmation'), styles.indexOf('@media (max-width: 1180px)', styles.indexOf('.default-confirmation')))
  const semanticStudioStyles = styles.replace(/:root\s*\{[^}]*\}/g, '')
  assert.doesNotMatch(semanticStudioStyles, /#[0-9a-fA-F]{3,8}\b/, 'studio UI outside semantic-token fallbacks must not hard-code light-theme colors')
  assert.doesNotMatch(specificationStyles, /#[0-9a-fA-F]{3,8}\b/, 'design specification shell must use Harness semantic tokens')
  assert.doesNotMatch(tweakStyles, /#[0-9a-fA-F]{3,8}\b/, 'design tweak shell must use Harness semantic tokens')
  assert.match(main, /设计依据/)
  assert.match(main, /AI 原型助手/)
  assert.match(main, /会结合当前 AI 对话/)
  assert.match(main, /需求清单优先/)
  assert.match(main, /title="安全交互原型"/)
  assert.match(main, /桌面/)
  assert.match(main, /平板/)
  assert.match(main, /手机/)
  assert.match(main, /sandbox="allow-scripts"/)
  assert.match(main, /referrerPolicy="no-referrer"/)
  assert.match(main, /event\.source !== frameRef\.current\?\.contentWindow/)
  assert.match(main, /prototype-selection-sync\/v1/)
  assert.match(main, /prototype-preview-mode\/v1/)
  assert.match(main, /isSandboxSelectionMessage/)
  assert.match(main, /isSandboxSelectionClearMessage/)
  assert.match(main, /isSandboxPreviewAuditMessage/)
  assert.match(main, /summarizePreviewAudit/)
  assert.match(main, /布局检查：/)
  assert.match(main, /检查全部尺寸/)
  assert.match(main, /previewStageLayout/)
  assert.match(main, /PREVIEW_VIEWPORT_WIDTHS/)
  assert.match(main, /prototype-preview-audit-request\/v1/)
  assert.match(main, /pendingPreviewAuditRef/)
  assert.match(main, /pendingPreviewAuditRef\.current = \{ viewport: next, requestId \}/)
  assert.match(main, /previewAuditReturnViewportRef\.current = previewViewportRef\.current/)
  assert.match(main, /const returnViewport = previewAuditReturnViewportRef\.current/)
  assert.match(main, /setPreviewViewport\(returnViewport\)/)
  assert.match(main, /choosePreviewViewport[\s\S]*previewAuditReturnViewportRef\.current = undefined/)
  assert.match(main, /summarizeAllPreviewAudits/)
  assert.match(main, /让 AI 修复当前尺寸/)
  assert.match(main, /Math\.abs\(frameWidth - expectedWidth\) > 2/)
  assert.match(main, /Math\.abs\(event\.data\.audit\.viewportWidth - expectedWidth\) > 2/)
  assert.match(main, /PROTOTYPE_REFERENCE_STORAGE_KEY/)
  assert.match(main, /validateReferenceEvidence/)
  assert.match(main, /verifyReferenceEvidenceFingerprint/)
  assert.match(main, /referenceId/)
  assert.match(main, /prototype-studio-snapshot\/v1/)
  assert.match(main, /prototype-studio-confirm-design\/v1/)
  assert.match(main, /prototype-studio-reopen-design\/v1/)
  assert.match(main, /prototype-studio-prompt\/v1/)
  assert.match(main, /prototype-studio-restore\/v1/)
  assert.match(main, /expectedCurrentRevisionId/)
  assert.match(main, /正在恢复…/)
  assert.match(main, /确认恢复/)
  assert.match(main, /恢复后仍可切回其他版本/)
  assert.match(main, /恢复前必须先读取并核对该版本与当前版本的差异/)
  assert.match(main, /确认恢复这个差异版本/)
  assert.match(main, /prepareRestore/)
  assert.match(main, /prototype-studio-revision-preview\/v1/)
  assert.match(main, /parseRevisionPreview/)
  assert.match(main, /只读预览/)
  assert.match(main, /返回当前版本/)
  assert.match(main, /当前版本安全预览/)
  assert.match(main, /历史版本安全预览/)
  assert.match(main, /srcDoc=\{srcDoc\}/)
  assert.match(main, /srcDoc=\{historySrcDoc\}/)
  assert.match(main, /historyPreview === undefined \? 'interact' : 'select'/)
  assert.match(main, /historyNonce, 'select'/)
  assert.match(main, /compareStageLayout\.viewportWidth/)
  assert.match(main, /if \(historyPreview !== undefined\) return/)
  assert.match(main, /history-compare/)
  assert.match(main, /historyFrameRef/)
  assert.match(main, /historyNonce/)
  assert.match(main, /mode: 'select'/)
  assert.match(main, /visualRevisionDiff/)
  assert.match(main, /页面与组件差异/)
  assert.match(main, /需求覆盖差异/)
  assert.match(main, /const historyPreviewReadOnly = historyPreview !== undefined/)
  assert.match(main, /当前是只读历史预览，请先返回当前版本，或恢复该版本后再修改。/)
  assert.match(main, /恢复后产品需求也会回到该版本。/)
  assert.match(main, /旧版未记录当时需求，恢复时会做兼容校验，可能被拒绝。/)
  assert.match(main, /historyPreview\.productBriefKnown/)
  assert.match(main, /if \(historyPreview !== undefined\) \{ setRequestTone\('info'\); setRequestStatus\('当前是只读历史预览/)
  assert.match(main, /disabled=\{sending \|\| waitingForRevision \|\| confirmingBrief \|\| historyPreviewReadOnly\}/)
  assert.match(main, /!confirmingBrief && !historyPreviewReadOnly/)
  assert.match(main, /先预览/)
  assert.match(main, /即将达到上限/)
  assert.match(main, /替换前会再次确认/)
  assert.match(main, /确认替换最旧版本并生成/)
  assert.match(main, /allowRevisionEviction/)
  assert.match(main, /先确认产品需求清单/)
  assert.match(main, /谁来使用/)
  assert.match(main, /必须包含的页面/)
  assert.match(main, /页面内关键模块/)
  assert.match(main, /必须演示的真实流程/)
  assert.match(main, /保存并确认需求清单/)
  assert.match(main, /开始生成原型/)
  assert.match(main, /prototype-studio-confirm-brief\/v1/)
  assert.match(main, /产品需求清单保存后未能完成同内容回读/)
  assert.match(main, /productBriefFingerprint/)
  assert.match(main, /sha256Fingerprint\(brief\)/)
  assert.match(main, /sha256Fingerprint\(refreshed\.productBrief\)/)
  assert.match(main, /applyBriefExample\('supplier'\)/)
  assert.match(main, /applyBriefExample\('project'\)/)
  assert.match(main, /AI 从当前对话整理需求/)
  assert.match(main, /prototype-studio-suggest-brief\/v1/)
  assert.match(main, /suggestedProductBrief/)
  assert.match(main, /briefSuggestionAttempt/)
  assert.match(main, /确认后才会用于原型/)
  assert.match(main, /productBriefFromFields/)
  assert.match(main, /已确认的产品需求/)
  assert.match(main, /需求验收/)
  assert.match(main, /流程由可信运行器逐步骤回放，不采用 AI 自评。/)
  assert.match(main, /可信运行器回放通过/)
  assert.match(main, /实际步骤：/)
  assert.match(main, /最后看到：/)
  assert.match(main, /定位页面/)
  assert.match(main, /定位控件/)
  assert.match(main, /prototype-coverage-focus\/v1/)
  assert.match(main, /productRequirementCoverage\(bundle\.value\.document, savedBrief\)/)
  assert.match(main, /当前版本的需求验收结果未通过确定性校验。/)
  assert.match(styles, /\.requirement-coverage/)
  assert.match(main, /更新产品需求/)
  assert.match(main, /更新产品需求并生成新版本/)
  assert.match(main, /确认需求变更并生成新版本/)
  assert.match(main, /取消更新/)
  assert.match(main, /当前版本仍使用旧需求；新版本通过校验并保存后才会更新。/)
  assert.match(main, /const requirementsUpdateActive = currentRevisionId !== undefined/)
  assert.match(main, /const isBriefEditor = currentRevisionId === undefined \|\| requirementsUpdateActive/)
  assert.match(main, /const requirementsChanged = draftBrief !== undefined/)
  assert.match(main, /const updatingRequirements = !firstGeneration && \(editingRequirements \|\| requirementsUpdateProject\.current === bundle\.projectId\)/)
  assert.match(main, /const localEdit = updatingRequirements \? undefined : selection/)
  assert.match(main, /selection: localEdit/)
  assert.match(main, /startRequirementsUpdate/)
  assert.match(main, /cancelRequirementsUpdate/)
  assert.match(main, /bundle\.currentRevisionId !== undefined && savedBrief !== undefined && draft !== undefined/)
  assert.match(main, /Keep it across an accidental refresh/)
  assert.match(styles, /\.accepted-brief-heading/)
  assert.match(styles, /\.requirements-update-note/)
  assert.match(styles, /\.history-brief-note/)
  assert.match(main, /snapshot\.productBrief/)
  assert.match(main, /loadProductBriefDraft/)
  assert.match(main, /saveProductBriefDraft/)
  assert.match(main, /clearProductBriefDraft/)
  assert.match(main, /loadPrototypeRequestDraft/)
  assert.match(main, /savePrototypeRequestDraft/)
  assert.match(main, /已恢复上次未发送的修改要求/)
  assert.match(main, /未确认草稿保存在当前标签页/)
  assert.match(main, /正在连接原型服务…/)
  assert.match(main, /不需要重新加载扩展/)
  assert.match(main, />重新检查</)
  assert.match(main, /className="studio-loading" role=\{error === undefined \? 'status' : 'alert'\} aria-live="polite"/)
  assert.match(main, /确认网页设计规范/)
  assert.match(html, /prototype-startup-guard\.js/)
  assert.doesNotMatch(html, /type="module" src="\/prototype-startup-guard\.js"/)
  assert.match(startupGuard, /AI 原型工具启动失败/)
  assert.match(startupGuard, /dataset\.prototypeStartupGuard = 'failed'/)
  assert.match(startupGuard, /unhandledrejection/)
  assert.match(startupGuard, /重新加载页面/)
  assert.match(startupGuard, /本地开发服务没有连接/)
  assert.match(main, /左侧检查全部规范，右侧直接操作示例页面；确认后才会交给 AI 生成原型/)
  assert.doesNotMatch(main, /review-reference-heading/)
  assert.doesNotMatch(main, /review-guide/)
  assert.match(main, /当前可见区域截图/)
  assert.match(main, /整页样式采样区域/)
  assert.match(main, /采集范围与未覆盖内容/)
  assert.match(main, /未覆盖或仅作推导/)
  assert.match(main, /采入 \/ 检查元素/)
  assert.match(main, /captureCoverageWarnings/)
  assert.match(main, /采集覆盖提醒/)
  assert.match(main, /设计规范来自整页多个纵向区域的样式采样/)
  assert.match(main, /evidence\[0\]!\.observations\.map/)
  assert.match(main, /这些规范组成的示例页面/)
  assert.match(main, /打开原网页核对/)
  assert.match(main, /exampleViewportWidths/)
  assert.match(main, /aria-label="示例页面尺寸"/)
  assert.match(main, /data-example-viewport={exampleViewport}/)
  assert.match(main, /px 布局示意 · 按钮均可操作/)
  assert.match(main, /设计规范快速目录/)
  assert.match(main, /交给 AI 的设计原则/)
  assert.match(main, /不包含隐藏规则/)
  assert.match(main, /designSpec\.principles\.map/)
  assert.match(main, /快速查看/)
  assert.match(main, /类未实测/)
  assert.match(main, /组件与交互状态/)
  assert.match(main, /字体文件/)
  assert.match(main, /图片 \/ Logo/)
  assert.match(main, /需要真实素材时由用户另行添加/)
  assert.match(main, /危险操作/)
  assert.match(main, /错误状态/)
  assert.match(main, /信息与业务状态/)
  assert.match(main, /网页实际发现/)
  assert.match(main, /CSS 声明的 hover、focus、active 等状态未被主动触发；未测视觉值不计入网页实测/)
  assert.match(main, /const responsiveSource =/)
  assert.match(main, /从 CSS 规则提取/)
  assert.match(main, /不可访问\/默认/)
  assert.match(main, /const cssStateStyle =/)
  assert.match(main, /右侧示例使用的 CSS 规则 token/)
  assert.match(main, /CSS 规则提取样式/)
  assert.match(styles, /\.evidence-provenance/)
  assert.match(styles, /\.css-state-samples/)
  assert.match(main, /实采 \{sample\.count\} 个/)
  assert.match(main, /未采到可稳定复现的组件样本/)
  assert.match(main, /网页未识别（安全默认）/)
  assert.match(main, /measuredValue/)
  assert.match(main, /表格 \/ 列表/)
  assert.match(main, /弹窗 \/ 抽屉/)
  assert.match(main, /示例只使用安全默认值展示，不把它当作网页证据/)
  assert.match(main, /Default 默认/)
  assert.match(main, /确认并交给 AI/)
  assert.match(main, /导出离线原型/)
  assert.match(main, /导出规范数据/)
  assert.match(main, /createPrototypeExportArtifacts/)
  assert.match(main, /重新调整规范/)
  assert.match(main, /基于同一参考创建新方案/)
  assert.match(main, /prototype-studio-create-variant\/v1/)
  assert.match(main, /旧原型和历史版本会完整保留/)
  assert.match(main, /重新调整后回读的原型状态不正确/)
  assert.match(main, /DesignSpecTweakPanel/)
  assert.match(main, /loadDesignSpecDraft\(window\.sessionStorage/)
  assert.match(main, /saveDesignSpecDraft\(window\.sessionStorage/)
  assert.match(main, /clearDesignSpecDraft\(window\.sessionStorage/)
  assert.match(main, /调整规范/)
  assert.match(main, /调整了 \$\{changedGroups\} 类规范/)
  assert.match(main, /用户已调整/)
  assert.match(main, /designSpecChangedGroups/)
  assert.match(main, /validateDesignSpec\(designSpec, bundle\.evidence/)
  assert.match(main, /requiresDefaultAcknowledgement/)
  assert.match(main, /designSpecQualityWarnings/)
  assert.match(main, /requiresReviewAcknowledgement/)
  assert.match(main, /可读性与操作提醒/)
  assert.match(main, /网页未识别，示例使用安全默认值/)
  assert.match(main, /确认前请核对/)
  assert.match(main, /我已经看过右侧示例页面/)
  assert.match(main, /type="checkbox" checked=\{defaultAcknowledged\}/)
  assert.match(main, /requiresReviewAcknowledgement && !defaultAcknowledged/)
  assert.match(main, /onClick=\{\(\) => onConfirm\(designSpec\)\}/)
  assert.doesNotMatch(main, /setDefaultAcknowledged\(true\); return/)
  assert.match(main, /页面语义颜色/)
  assert.match(main, /动效时长/)
  assert.match(main, /控件圆角/)
  assert.match(main, /普通表面投影/)
  assert.match(main, /弹窗与菜单投影/)
  assert.match(main, /主按钮渐变/)
  assert.match(main, /禁用控件透明度/)
  assert.match(main, /仅使用产品内置安全图标/)
  for (const token of ['control-radius', 'icon-size', 'disabled-opacity', 'surface-shadow', 'elevated-shadow', 'section-gap', 'content-width']) assert.match(main, new RegExp(`--review-${token}`))
  assert.match(main, /px 布局示意 · 按钮均可操作/)
  assert.match(main, /aria-pressed=\{exampleSection === 'workspace'\}/)
  assert.match(main, /aria-pressed=\{exampleFilter === 'active'\}/)
  assert.match(main, /nextExampleTab\(previewTab, event\.key\)/)
  assert.match(main, /tab\.tabIndex = index === \(previewTab === 'overview' \? 0 : 1\) \? 0 : -1/)
  assert.match(main, /tabList\.addEventListener\('keydown', navigateTabs\)/)
  assert.match(main, /已创建“\$\{name\}”示例项目/)
  assert.match(main, /exampleFeedback !== undefined/)
  assert.match(main, /role=\{requestTone === 'error' \? 'alert' : 'status'\}/)
  assert.match(main, /操作原型/)
  assert.match(main, /选择修改/)
  assert.match(main, /onLoad=\{syncPreviewState\}/)
  assert.match(main, /if \(mode === 'interact'\) setSelection\(undefined\)/)
  assert.match(main, /onClick=\{\(\) => choosePreviewMode\('interact'\)\}>改为调整整个原型/)
  assert.match(main, /返回原型编辑器/)
  assert.match(main, /这套规范已经安全锁定/)
  assert.match(main, /正在保存并核对/)
  assert.match(main, /保存后未能回读确认/)
  assert.match(main, /保存后回读的设计规范与刚才确认的内容不一致/)
  assert.match(main, /sha256Fingerprint\(checked\.value\)/)
  assert.match(main, /response\.result\?\.designSpecFingerprint !== expectedFingerprint/)
  assert.match(main, /sha256Fingerprint\(refreshed\.designSpec\) !== expectedFingerprint/)
  assert.match(main, /AI 正在生成并校验/)
  assert.match(main, /正在创建新方案…/)
  assert.match(main, /新方案已在新标签页打开。/)
  assert.match(main, /setCreateVariantSuccess/)
  assert.match(main, /你的要求会保留，失败后可直接重试/)
  assert.match(main, /attempt\.expectedRevisionId !== undefined && attempt\.prompt !== undefined/)
  assert.match(main, /setRequest\(attempt\.prompt\)/)
  assert.match(main, /requestId = crypto\.randomUUID\(\)/)
  assert.match(main, /requestId, prompt: outgoingPrompt/)
  assert.match(main, /brief === undefined \? \{\} : \{ brief \}/)
  assert.match(main, /generationTimedOut/)
  assert.match(main, /尚未收到保存结果/)
  assert.match(main, /刷新生成状态/)
  assert.match(main, /停止本次生成/)
  assert.match(main, /确认停止生成/)
  assert.match(main, /prototype-studio-cancel-generation\/v1/)
  assert.match(main, /hasStoppedGeneration\(requestId, refreshed\.generationAttempt\)/)
  assert.match(main, /if \(attempt === undefined\) return/)
  assert.match(main, /attempt\.status === 'error'/)
  assert.match(main, /上次生成未能保存/)
  assert.match(main, /generationAttempt/)
  assert.match(main, /已恢复正在处理的生成请求/)
  assert.match(main, /setGenerationTimedOut\(true\)/)
  assert.doesNotMatch(main, /setWaitingForRevision\(false\); setRequestTone\('error'\); setRequestStatus\('AI 暂时还没有保存新版本/)
  assert.match(main, /AI 多次保存仍未通过/)
  assert.match(main, /正在等待它根据具体错误修正/)
  assert.match(main, /visibilitychange/)
  assert.match(main, /studioAttempt/)
  assert.match(main, /studioGenerationAttempt/)
  assert.match(main, /studioRevisions/)
  assert.match(main, /版本历史不匹配/)
  assert.match(main, /disabled=\{sending \|\| waitingForRevision \|\| confirmingBrief\}/)
  assert.match(main, /⌘\/Ctrl \+ Enter 发送/)
  assert.match(main, /if \(!designConfirmed\)/)
  assert.match(main, /exampleModalRef\.current\?\.querySelectorAll/)
  assert.match(main, /window\.document\.activeElement === last/)
  assert.match(main, /exampleTriggerRef\.current\?\.focus/)
  assert.match(styles, /\.review-layout/)
  assert.match(styles, /\.spec-block \{ scroll-margin-top: 110px;/)
  assert.match(styles, /\.review-source \{ position: static; grid-column: 1 \/ -1; grid-template-columns: 160px minmax\(0, 1fr\) auto;/)
  assert.match(styles, /--studio-business-primary:\s*var\(--dsw-alias-state-business-primary,/)
  assert.match(styles, /--studio-label-primary:\s*var\(--dsw-alias-label-primary,/)
  assert.match(styles, /--studio-bg-layer-2:\s*var\(--dsw-alias-bg-layer-2,/)
  assert.match(styles, /--studio-border-l3:\s*var\(--dsw-alias-border-l3,/)
  assert.match(styles, /--studio-success:\s*var\(--dsw-alias-state-success-primary,/)
  assert.match(styles, /@media \(prefers-color-scheme: dark\)/)
  assert.match(styles, /color-scheme:\s*dark/)
  assert.match(styles, /--studio-bg-base:\s*var\(--dsw-alias-bg-base,\s*#111318\)/)
  assert.match(styles, /--studio-label-primary:\s*var\(--dsw-alias-label-primary,\s*#f3f4f6\)/)
  assert.doesNotMatch(styles, /\.review-guide/)
  assert.doesNotMatch(styles, /\.review-reference-heading/)
  assert.doesNotMatch(styles, /\.review-flow/)
  assert.match(styles, /\.review-warnings/)
  assert.match(styles, /\.review-acknowledgement/)
  assert.match(styles, /\.semantic-color-grid/)
  assert.match(styles, /\.spec-index/)
  assert.match(styles, /\.principles-list/)
  assert.match(styles, /\.review-steps/)
  assert.match(styles, /\.component-preview/)
  assert.match(styles, /\.component-evidence-grid/)
  assert.match(styles, /\.example-provenance/)
  assert.match(styles, /\.example-project-row/)
  assert.match(styles, /\.example-feedback/)
  assert.match(styles, /\.example-viewport-switch/)
  assert.match(styles, /\.example-tablet \.example-grid/)
  assert.match(styles, /\.example-mobile \.example-grid/)
  assert.match(styles, /\.example-page button:disabled, \.example-page input:disabled \{ opacity: var\(--review-disabled-opacity\); \}/)
  assert.match(styles, /\.example-modal, \.example-profile, \.example-feedback \{ box-shadow: var\(--review-elevated-shadow\); \}/)
  assert.match(styles, /\.example-hero, \.example-grid, \.component-preview \{ width: min\(100%, var\(--review-content-width\)\)/)
  assert.match(styles, /max\(160px, calc\(var\(--review-content-width\) - var\(--review-space-large\) \* 2\)\)/)
  assert.match(styles, /\.tweak-panel/)
  assert.match(styles, /\.tweak-colors/)
  assert.match(styles, /\.prototype-scale-stage/)
  assert.match(styles, /transform-origin:\s*top left/)
  assert.match(styles, /\.preview-audit/)
  assert.match(styles, /\.history-preview-banner/)
  assert.match(styles, /\.history-compare/)
  assert.match(styles, /\.history-diff-summary/)
  assert.match(styles, /@media \(max-width: 900px\) \{ \.history-compare \{ grid-template-columns: 1fr;/)
  assert.match(styles, /\.restore-diff/)
  assert.match(styles, /\.brief-builder/)
  assert.match(styles, /\.brief-status/)
  assert.match(styles, /\.accepted-brief/)
  assert.match(styles, /\.revision-eviction-confirm/)
  assert.match(styles, /\.version-row/)
  assert.match(styles, /\.audit-actions/)
  assert.match(styles, /\.capture-details/)
  assert.match(styles, /\.review-footer-actions/)
  assert.match(styles, /\.variant-success/)
  assert.match(styles, /--review-heading/)
  assert.match(styles, /\.danger-action/)
  assert.match(styles, /@media \(max-width: 1000px\)/)
  assert.match(styles, /@media \(max-width: 720px\)/)
  assert.match(main, /before-first-generation/)
  assert.match(main, /has-revision/)
  assert.match(styles, /\.studio-shell\.before-first-generation \.ai-panel \{ order: 2;/)
  assert.match(styles, /\.studio-shell\.before-first-generation \.preview-panel \{ order: 3;/)
  assert.match(styles, /\.coverage-status\.adjusted/)
  assert.match(styles, /grid-template-columns:\s*minmax\(220px, \.8fr\) minmax\(420px, 1\.6fr\) minmax\(240px, \.9fr\)/)
})

test('design-spec number fields allow editing before committing or reverting', async () => {
  const panel = await readFile(new URL('./DesignSpecTweakPanel.tsx', import.meta.url), 'utf8')
  assert.match(panel, /useState\(String\(value\)\)/)
  assert.match(panel, /onBlur=\{commit\}/)
  assert.match(panel, /event\.key === 'Enter'/)
  assert.match(panel, /event\.key === 'Escape'/)
  assert.doesNotMatch(panel, /valueAsNumber/)
  assert.match(panel, /浮层表面/)
  assert.match(panel, /控件圆角/)
  assert.match(panel, /弹窗与菜单投影/)
  assert.match(panel, /高级调整/)
  assert.match(panel, /完整排版梯度/)
  assert.match(panel, /间距梯度/)
  assert.match(panel, /不提供任意 CSS 输入/)
  assert.match(panel, /撤销上一项/)
  assert.match(panel, /恢复网页提取值/)
  assert.match(panel, /窄屏断点/)
  assert.match(panel, /宽屏断点/)
  assert.match(panel, /透明度/)
  assert.match(panel, /动效曲线/)
})
