import assert from 'node:assert/strict'
import { readFile } from 'node:fs/promises'
import test from 'node:test'

const read = relative => readFile(new URL(`../${relative}`, import.meta.url), 'utf8')

test('keeps the e327 compact picker in an out-of-tree public workspace seat', async () => {
  const [client, picker, css, actions] = await Promise.all([
    read('src/client/index.ts'), read('src/client/CompactWorkspacePicker.tsx'), read('src/client/CompactWorkspacePicker.module.css'),
    read('src/client/WorkspaceSurfaceActions.tsx'),
  ])
  assert.match(client, /sidebar\.workspaces\.compact/)
  assert.match(
    client,
    /name:\s*'sidebar\.workspaces\.compact'[\s\S]*?select:\s*_owner\s*=>\s*claudeImport[\s\S]*?CompactWorkspacePicker/,
    'chain workspace registration must select the matched owner',
  )
  assert.match(picker, /requestWorkspaceAdd/)
  assert.match(picker, /owner\.directoryFlow/)
  assert.match(picker, /document\.addEventListener\('pointerdown'/)
  assert.match(picker, /event\.key !== 'Escape'/)
  assert.match(picker, /function classes\(/)
  assert.doesNotMatch(picker, /from 'clsx'/)
  assert.match(picker, /IconEllipsisOutline16/)
  assert.match(actions, /IconDownloadOutline16/)
  assert.match(picker, /IconNewChatOutline16/)
  assert.match(picker, /css\.verticalEllipsis/)
  assert.match(picker, /owner\.startSession\(selectedWorkspace\?\.id\)/)
  assert.match(picker, /owner\.startSession\(workspace\.id\)/)
  assert.match(actions, /从 Claude Code 导入/)
  assert.match(actions, /ClaudeImportModal/)
  assert.match(picker, /ClaudeImportAction/)
  assert.match(picker, /claudeImportControllerOf\(owner\)/)
  assert.match(actions, /disabled=\{controller === undefined \|\| workspace === undefined\}/)
  assert.match(picker, /owner\.renameWorkspace/)
  assert.match(picker, /owner\.deleteWorkspace/)
  assert.match(picker, /id: 'open'/)
  assert.match(picker, /id: 'rename'/)
  assert.match(picker, /id: 'delete'/)
  assert.match(picker, /owner\.openPath\(workspace\.path\)/)
  assert.match(picker, /owner\.labels\.openFolder/)
  assert.match(picker, /side="right"/)
  assert.match(picker, /owner\.labels\.deleteWorkspace/)
  assert.match(picker, /SessionRow/)
  assert.match(picker, /owner\.renameSession/)
  assert.match(picker, /owner\.forkSession/)
  assert.match(picker, /owner\.archiveSession/)
  assert.match(picker, /sessionRenameTitle/)
  assert.match(picker, /sessionActionsAria/)
  assert.match(picker, /aria-haspopup="menu"/)
  assert.match(picker, /aria-expanded=\{menuOpen\}/)
  assert.match(picker, /workspaceActionsAria/)
  assert.match(css, /\.popover\s*\{[^}]*display:\s*flex;/s, 'the compact picker must use a non-growing two-pane layout')
  assert.match(css, /\.popover\s*>\s*\.pane:first-child\s*\{[^}]*flex:\s*0\s+0\s+180px;[^}]*width:\s*180px;[^}]*overflow-x:\s*hidden;/s, 'the workspace pane must stay fixed-width and never expose horizontal scrolling')
  assert.match(css, /\.popover\s*>\s*\.pane:first-child\s+\.list\s*\{[^}]*overflow-x:\s*hidden;/s, 'the workspace list itself must not turn its vertical scroller into a horizontal one')
  assert.match(css, /\.sessionsPane\s*\{[^}]*flex:\s*1;[^}]*min-width:\s*0;/s, 'the sessions pane must retain the remaining width without forcing the workspace pane wider')
  assert.match(picker, /css\.paneHeader[\s\S]*labels\.workspaces[\s\S]*css\.paneHeader[\s\S]*labels\.sessions/, 'both pane titles must share the same header row')
  assert.match(css, /\.paneHeader\s*\{[^}]*box-sizing:\s*border-box;[^}]*align-items:\s*center;[^}]*height:\s*32px;/s, 'workspace and session titles must occupy the same header height')
  assert.match(css, /\.paneTitle\s*\{[^}]*display:\s*flex;[^}]*align-items:\s*center;[^}]*height:\s*28px;[^}]*line-height:\s*16px;/s, 'pane titles must share the same text box as the add-workspace control')
  assert.match(css, /\.row\s*\{[^}]*box-sizing:\s*border-box;[^}]*min-width:\s*0;[^}]*overflow:\s*hidden;/s, 'picker rows must keep padding inside the pane and never overflow it')
  assert.match(css, /\.folder\s*\+\s*span\s*\{[^}]*min-width:\s*0;[^}]*overflow:\s*hidden;[^}]*text-overflow:\s*ellipsis;[^}]*white-space:\s*nowrap;/s, 'long workspace names must truncate on one line')
  assert.match(css, /\.count\s*\{[^}]*flex-shrink:\s*0;/s, 'the workspace session count must remain visible')
  assert.match(css, /\.rowActions\s*\{[^}]*flex-shrink:\s*0;/s, 'hover actions must keep their full icon width')
  assert.match(css, /\.iconButton\s*\{[^}]*width:\s*20px;[^}]*height:\s*20px;/s, 'hover icons must keep a fixed hit target')
  assert.match(css, /\.row:hover \.count,\s*\.rowMenuOpen \.count\s*\{[^}]*display:\s*none;/s, 'hover and an open menu must hide the session count')
  assert.match(css, /\.row:hover \.rowActions,\s*\.rowMenuOpen \.rowActions\s*\{[^}]*display:\s*inline-flex;/s, 'hover and an open menu must reveal new-session plus the actions menu')
  assert.match(css, /\.headerActions\s*\{[^}]*display:\s*inline-flex;/s, 'session header must keep the two icon actions together')
  assert.match(css, /\.sessionRow:hover \.sessionTime, \.sessionRow\.rowMenuOpen \.sessionTime\s*\{[^}]*display:\s*none;/s, 'session hover must replace time with the actions icon')
  assert.match(css, /\.sessionRow:hover \.sessionRowActions, \.sessionRow\.rowMenuOpen \.sessionRowActions\s*\{[^}]*display:\s*inline-flex;/s, 'session hover must reveal the actions icon')
  assert.match(css, /\.verticalEllipsis\s*\{[^}]*transform:\s*rotate\(90deg\)/s, 'session actions must use a vertical ellipsis icon')
  assert.match(css, /@media \(max-width: 360px\)/)
})

test('Claude Code import stays bounded, on-demand, cancellable, and uses public session verbs', async () => {
  const [host, directory, client, modal] = await Promise.all([
    read('src/index.ts'), read('src/claude-import.mjs'), read('src/client/index.ts'), read('src/client/ClaudeImportModal.tsx'),
  ])
  assert.match(host, /loopback same-origin/)
  assert.match(directory, /MAX_PROJECTS = 500/)
  assert.match(directory, /MAX_SOURCE_BYTES = 8 \* 1024 \* 1024/)
  assert.match(directory, /MAX_SESSION_PAGE_SIZE = 64/)
  assert.match(directory, /readPrefix\(file, MAX_PREVIEW_BYTES\)/)
  assert.match(directory, /kind: 'existing'/)
  assert.match(directory, /await realpath\(requested\)/)
  assert.match(directory, /this\.registryMutation = operation/)
  assert.match(directory, /randomUUID\(\)/)
  assert.match(client, /ctx\.workspaces\.connectWorkspace/)
  assert.match(client, /session\.prompt/)
  assert.match(client, /session\.rename/)
  assert.match(client, /ctx\.sessions\.open/)
  assert.match(modal, /AbortController/)
  assert.match(modal, /已读取 \{sessions\.length\} \/ \{sessionsTotal/)
  assert.match(modal, /<progress/)
  assert.match(modal, /Claude projects 来源目录/)
  assert.match(modal, /恢复默认/)
  assert.match(modal, /创建会话并提交上下文，此阶段不能撤回/)
  assert.match(modal, /重新导入为副本/)
  assert.match(client, /input\.signal\?\.aborted/)
  assert.match(host, /req\.once\('aborted'/)
  assert.match(host, /signal: controller\.signal/)
  assert.doesNotMatch(modal, /<Modal\b/, 'Claude import must own a full-content shell instead of the centered primitive card')
  assert.match(modal, /createPortal/)
  assert.match(modal, /data-testid="claude-import-overlay"/)
  assert.match(modal, /className=\{css\.importPanel\}[\s\S]*role="dialog"[\s\S]*aria-modal="true"/)
  const css = await read('src/client/CompactWorkspacePicker.module.css')
  assert.match(css, /\.importOverlay\s*\{[^}]*position:\s*fixed;[^}]*inset:\s*0;/s)
  assert.match(css, /\.importPanel\s*\{[^}]*width:\s*100%;[^}]*height:\s*100%;[^}]*min-height:\s*0;/s)
  assert.match(css, /\.importMain\s*\{[^}]*flex:\s*1;[^}]*min-height:\s*0;/s)
  assert.match(css, /\.importGrid\s*\{[^}]*flex:\s*1;[^}]*min-height:\s*0;/s)
  assert.match(css, /@media \(max-width:\s*440px\)/)
  assert.doesNotMatch(css, /\.importGrid\s*\{[^}]*height:\s*min\(360px/s)
  assert.doesNotMatch(`${host}\n${directory}\n${client}`, /upstream\/deepseek-harness\/packages\/.*\/src/)
})

test('the compact seat owner exposes workspace rename, delete, and new-session actions', async () => {
  const patch = await readFile(new URL('../../../upstream-contributions/0006-workspace-compact-seat.patch', import.meta.url), 'utf8')
  assert.match(patch, /renameSession, forkSession, renameWorkspace, deleteWorkspace, openPath, archiveSession,/)
  assert.match(patch, /workspaceActionsAria: name => t\('actions\.workspace\.aria', \{ name \}\)/)
  assert.match(patch, /newSessionAria: name => t\('actions\.newSession\.aria', \{ name \}\)/)
  assert.match(patch, /path: workspace\.path/)
  assert.match(patch, /createdAt: Date\.parse\(workspace\.createdAt\)/)
  assert.match(patch, /renameWorkspace: \(workspaceId: WorkspaceId, title: string\) => Promise<void>/)
  assert.match(patch, /deleteWorkspace: \(workspaceId: WorkspaceId\) => Promise<void>/)
  assert.match(patch, /openPath: \(path: string\) => Promise<void>/)
  assert.match(patch, /openFolder: t\('open\.folder'\)/)
  assert.match(patch, /openPath: async \(path\) => \{ await ctx\.workspaces\.openPath\(path\) \}/)
})

test('wide workspace browser preserves its official list and exposes Claude import plus open-folder menu action', async () => {
  const [patch, client] = await Promise.all([
    readFile(new URL('../../../upstream-contributions/0021-workspace-column-action-seams.patch', import.meta.url), 'utf8'),
    read('src/client/index.ts'),
  ])
  assert.match(patch, /'sidebar\.workspaces\.header\.action': \{ kind: 'list'; scope: 'root'; owner: WorkspaceHeaderActionOwnerProps \}/)
  assert.match(patch, /renderSlot\('sidebar\.workspaces\.header\.action', \{ workspace: actionWorkspace \}\)/)
  assert.match(patch, /\{ id: 'open', label: t\('open\.folder'\), icon: <IconFolderOpen16 \/> \}/)
  assert.match(patch, /if \(id === 'open'\) actions\.openPath\(\)/)
  assert.match(patch, /openPath: \(\) => \{[\s\S]*void openPath\(workspace\.path\)/)
  assert.match(patch, /actions=\{\{ openPath: vi\.fn\(\), rename: onRename, delete: onDelete \}\}/)
  assert.match(client, /ctx\.slots\.inject\('sidebar\.workspaces\.header\.action'/)
  assert.doesNotMatch(patch, /sidebar\.workspaces\.workspace\.action/)
  assert.doesNotMatch(client, /sidebar\.workspaces\.workspace\.action/)
  assert.doesNotMatch(client, /ctx\.slots\.inject\('sidebar\.workspaces',/, 'the product must extend the official column browser rather than replace it')
})

test('wide Claude import remains visible with a clear enabled and disabled label', async () => {
  const [actions, client, css, patch] = await Promise.all([
    read('src/client/WorkspaceSurfaceActions.tsx'),
    read('src/client/index.ts'),
    read('src/client/CompactWorkspacePicker.module.css'),
    readFile(new URL('../../../upstream-contributions/0021-workspace-column-action-seams.patch', import.meta.url), 'utf8'),
  ])
  assert.match(actions, /variant\?: 'compact' \| 'header'/)
  assert.match(actions, /导入 Claude Code/)
  assert.match(actions, /创建工作区后导入/)
  assert.match(actions, /css\.importActionSlot/)
  assert.match(client, /createWorkspaceHeaderClaudeImportAction\(claudeImport\)/)
  assert.doesNotMatch(client, /name: 'sidebar\.workspaces\.header\.action'[\s\S]*select:/)
  assert.match(css, /\.importWorkspace\s*\{[^}]*min-width:\s*128px;[^}]*white-space:\s*nowrap;/s)
  assert.match(patch, /-  max-width: 60px;\n\+  max-width: none;/)
})
