import assert from 'node:assert/strict'
import { readFile } from 'node:fs/promises'
import test from 'node:test'

const source = path => readFile(new URL(`../${path}`, import.meta.url), 'utf8')

test('keeps prototype preview as an out-of-tree, schema-only product package', async () => {
  const [manifest, schema, runtime, host] = await Promise.all([source('package.json'), source('src/prototype-document.ts'), source('src/client/TrustedPrototypeRuntime.tsx'), source('src/index.ts')])
  assert.match(manifest, /@accrui\/harness-ui-prototype-studio/)
  assert.match(manifest, /"inject"/)
  assert.match(schema, /ReferenceEvidenceV1/)
  assert.match(schema, /DesignSpecV1/)
  assert.match(schema, /PrototypeDocumentV1/)
  assert.match(schema, /PrototypeRevisionV1/)
  assert.match(schema, /'navigate' \| 'open-modal' \| 'close-modal' \| 'set-value' \| 'set-state' \| 'toggle' \| 'set-tab' \| 'submit-success' \| 'sequence'/)
  assert.match(runtime, /validatePrototypeBundle/)
  assert.match(schema, /validatePrototypeBundle/)
  assert.match(schema, /createTrustedRevision/)
  assert.match(schema, /verifyTrustedRevision/)
  assert.match(runtime, /data-prototype-element-id/)
  assert.match(runtime, /selectPart\(row\.id, 'table-row'/)
  assert.match(runtime, /selectPart\(item\.id, 'list-item'/)
  assert.match(runtime, /selectPart\(tab\.id, 'tab'/)
  assert.match(runtime, /event\.stopPropagation\(\); select\(node\); act\(node\.action\)/)
  assert.match(host, /save_product_prototype/)
  assert.match(host, /PROTOTYPE_STUDIO_RESTORE_PATH/)
  assert.match(host, /PROTOTYPE_STUDIO_RECOVER_PATH/)
  assert.match(host, /verifiedRecoveryAssertion\(body\.assertion, body\.signature, body\.capability\)/)
  assert.match(host, /DSH_PROTOTYPE_RECOVERY_PUBLIC_KEY/)
  assert.match(host, /item\.runId !== recoveryRunId/)
  assert.match(host, /item\.capabilityFingerprint/)
  assert.match(host, /expiresAt <= now/)
  assert.match(host, /expiresAt > issuedAt \+ 60_000/)
  assert.match(host, /verify\(null, bytes, recoveryPublicKey, signatureBytes\)/)
  assert.match(host, /expectedRecoveryEpoch/)
  assert.match(host, /nonce/)
  assert.doesNotMatch(host, /recoveryBearer\(req\)|explicitUserAction|DSH_PROTOTYPE_RECOVERY_TOKEN/)
  assert.match(host, /recoverCapability/)
  assert.match(host, /PROTOTYPE_STUDIO_CONFIRM_DESIGN_PATH/)
  assert.match(host, /PROTOTYPE_STUDIO_REOPEN_DESIGN_PATH/)
  assert.match(host, /confirmDesign/)
  assert.match(host, /reopenDesign/)
  assert.match(host, /Invalid design specification reopening request/)
  assert.match(host, /candidateProjectId/)
  assert.match(host, /recordFailure/)
  assert.match(host, /PROTOTYPE_STUDIO_BEGIN_GENERATION_PATH/)
  assert.match(host, /PROTOTYPE_STUDIO_CANCEL_GENERATION_PATH/)
  assert.match(host, /request_id/)
  assert.match(host, /targetRevisionId/)
  assert.match(host, /expectedCurrentRevisionId/)
  assert.match(host, /verified_write/)
  assert.doesNotMatch(`${schema}\n${runtime}`, /new Function|\beval\s*\(|innerHTML|deepseek-harness\/packages\/.*\/src/)
})
