import assert from 'node:assert/strict'
import { readFile } from 'node:fs/promises'
import test from 'node:test'

test('trusted React runtime uses bounded state for visible content and keeps selection mode read-only', async () => {
  const [source, styles] = await Promise.all([readFile(new URL('../src/client/TrustedPrototypeRuntime.tsx', import.meta.url), 'utf8'), readFile(new URL('../src/client/TrustedPrototypeRuntime.module.css', import.meta.url), 'utf8')])
  assert.match(source, /export type PrototypeRuntimeMode = 'interact' \| 'select'/)
  assert.match(source, /node\.visibleWhen === undefined \|\| state\.stateValues\[node\.visibleWhen\.stateId\] === node\.visibleWhen\.equals/)
  assert.match(source, /mode === 'interact' && action !== undefined/)
  assert.match(source, /bindStateId: node\.bindStateId/)
  assert.match(source, /if \(mode === 'select'\) event\.preventDefault\(\)/)
  assert.match(source, /modalNodes\(screen\.nodes, state\)/)
  assert.match(source, /--prototype-positive/)
  assert.match(source, /--prototype-warning/)
  assert.match(source, /--prototype-danger/)
  assert.match(source, /--prototype-on-danger/)
  assert.match(source, /--prototype-border-style/)
  assert.match(source, /--prototype-control-radius/)
  assert.match(source, /--prototype-section-gap/)
  assert.match(source, /--prototype-disabled-opacity/)
  assert.match(source, /--prototype-surface-shadow/)
  assert.match(source, /--prototype-elevated-shadow/)
  assert.match(source, /prototypeDesignTokens\(designSpec\)\.compactBreakpoint/)
  assert.match(source, /runtime\.dataset\.prototypeCompact/)
  assert.match(source, /event\.key !== 'Tab'/)
  assert.match(source, /focusOriginRef\.current\?\.focus\(\)/)
  assert.match(source, /event\.target === event\.currentTarget/)
  assert.match(source, /document\.shell/)
  assert.match(source, /navigation-item/)
  assert.match(source, /node\.type === 'breadcrumb'/)
  assert.match(source, /selectPart\(item\.id, 'breadcrumb-item', item\.label\)/)
  assert.match(source, /<b data-prototype-element-id=\{item\.id\} data-prototype-selected=\{selectedElementId === item\.id \? 'true' : undefined\} tabIndex=\{mode === 'select' \? 0 : undefined\} onClick=\{event => \{ event\.stopPropagation\(\); if \(mode === 'select'\) selectPart\(item\.id, 'breadcrumb-item'/)
  assert.match(source, /onKeyDown=\{event => selectOnKey\(event, \(\) => selectPart\(item\.id, 'breadcrumb-item'/)
  assert.match(source, /node\.type === 'empty-state'/)
  assert.match(source, /node\.type === 'pagination'/)
  assert.match(source, /const rows = crudRows\(node\.id\); const hasActions = rows\.some\(row => row\.action !== undefined\)/)
  assert.match(source, /isCrudAction\(action\)/)
  assert.match(source, /pendingDelete/)
  assert.match(source, /type TableRuntimeState = Record<string, \{ page: number; sortDirection: 'asc' \| 'desc' \}>/)
  assert.match(source, /node\.filters \?\? \[\]/)
  assert.match(source, /filter\.operator === 'equals'/)
  assert.match(source, /node\.sort\?\.columnKey === column\.key/)
  assert.match(source, /node\.pagination !== undefined/)
  assert.match(source, /mode === 'select'\) select\(node\); else setTable/)
  assert.match(source, /tabIndex=\{mode === 'select' \? 0 : undefined\}[\s\S]*selectPart\(row\.id, 'table-row'/)
  assert.match(source, /<tr key=\{row\.id\}[\s\S]*onClick=\{event => \{ event\.stopPropagation\(\); if \(mode === 'select'\) selectPart\(row\.id, 'table-row'/)
  assert.match(source, /onKeyDown=\{event => selectOnKey\(event, \(\) => selectPart\(row\.id, 'table-row'/)
  assert.match(source, /<th scope="col">操作<\/th>/)
  assert.match(source, /打开详情/)
  assert.match(source, /item\.action === undefined \? <div/)
  assert.match(source, /aria-live="polite">当前页面：\{screen\.title\}/)
  assert.match(source, /node\.required/)
  assert.match(source, /aria-invalid/)
  assert.match(source, /prototypeInputHasValidationError/)
  assert.match(source, /firstInvalidId/)
  assert.match(source, /\.focus\(\)/)
  assert.match(source, /const fieldEffects = resolveFieldEffects\(document, state\)/)
  assert.match(source, /document\.fieldRules \?\? \[\]/)
  assert.match(source, /fieldEffects\.get\(node\.id\)\?\.disabled === true/)
  assert.match(source, /node\.text\.replace\(/)
  assert.match(source, /disabled=\{disabled && mode !== 'select'\}/)
  assert.match(source, /aria-disabled=\{disabled \|\| undefined\}/)
  assert.match(source, /const selectOnKey/)
  assert.match(source, /event\.key !== 'Enter' && event\.key !== ' '/)
  assert.match(source, /event\.key === 'Escape'/)
  assert.match(source, /tabIndex: mode === 'select' \? 0 : undefined/)
  assert.match(source, /tabIndex=\{tab\.id === active \? 0 : -1\}/)
  assert.match(source, /\['ArrowLeft', 'ArrowRight', 'Home', 'End'\]/)
  assert.match(styles, /\.breadcrumb/)
  assert.match(styles, /\.emptyState/)
  assert.match(styles, /\.pagination/)
  assert.match(styles, /\.inputError/)
  assert.match(styles, /var\(--prototype-positive/)
  assert.match(styles, /var\(--prototype-warning/)
  assert.match(styles, /var\(--prototype-danger/)
  assert.match(styles, /var\(--prototype-on-danger/)
  assert.match(styles, /\.button\.primary \{ background-image: var\(--prototype-gradient/)
  assert.match(styles, /var\(--prototype-surface-shadow/)
  assert.match(styles, /var\(--prototype-elevated-shadow/)
  assert.match(styles, /border-style: var\(--prototype-border-style/)
  assert.match(styles, /var\(--prototype-disabled-opacity/)
  assert.match(styles, /data-prototype-compact/)
  assert.match(styles, /\.tableSort/)
  assert.match(styles, /\.tablePagination/)
  assert.doesNotMatch(source, /innerHTML|new Function|\beval\s*\(/)
})
